### PR TITLE
Add trigger guide

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1574

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1644
- https://github.com/openmpf/openmpf-components/pull/336
- https://github.com/openmpf/openmpf-contrib-components/pull/88
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/121
- https://github.com/openmpf/openmpf-python-component-sdk/pull/71
- https://github.com/openmpf/openmpf-java-component-sdk/pull/63

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> Reviewed 29 of 32 files at r1, 41 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — COMMENTED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/171#-Nh80n7_2FDnvnfY5-GG:-Nh80n7_2FDnvnfY5-GH:be4yuqx) (no related file):*
Please remove the `GetDetectionType()` from the SDK docs. Also, `trackType` needs to be added to "Component Descriptor Reference".

___

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: 35 of 50 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/171#-Nh80n7_2FDnvnfY5-GG:-NiKCdM55d-pcqH-103B:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove the `GetDetectionType()` from the SDK docs. Also, `trackType` needs to be added to "Component Descriptor Reference".
</blockquote></details>

Done.

___

**Review by jrobble — APPROVED** [review]
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/171)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/docs/Trigger-Guide.md` line 188 at r7](https://reviewable.io/reviews/openmpf/openmpf.github.io/171#-Nijs7eY7m4YzZuSpx4C:-Nijs7eb8wrNZveXmtwZ:bld20u4) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/898eb1d520c3777fe1a78706f4b68f791e7463b4/docs/docs/Trigger-Guide.md#L188)):*
> ```Markdown
> that will later satisfy the trigger for stage 4.
> 
> Also, note that stages 1, 2, and 3 can all accept an optional `WHITELIST_FILE` property that can be
> ```

This section will need to be changed to "approved list" once your other PR lands. I will leave a comment on that.

**Pull request merged**
