### PR TITLE
Add Markup Guide.

### PR DESCRIPTION
**Pull request by jrobble**
Add Distribution and Licensing page.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/125)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/125)* status: 3 of 55 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/Distribution-And-Licensing.md, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWUXltw94mJO2VkVaFv:-MWUXltw94mJO2VkVaFw:b4rwjta) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Distribution-And-Licensing.md#L8)):*
> ```Markdown
> =====================
> 
> The Open Media Processing Framework (OpenMPF) software is provided as raw source code. This is to avoid any potential licensing issues that may arise from distributing a pre-compiled executable that is linked to dependencies that are licensed under a copyleft license or have patent restrictions. Generally, it is acceptable to build and execute software with these dependencies for non-commercial in-house use.
> ```

I don't know why you do this to yourself. You can wrap long lines. 

These two produce identical output:
```
This is sample text. This is more text.

This is another paragraph.
```


```
This is 
sample text. 
This is 
more 
text.

This is another 
paragraph.
```
___
*[docs/docs/Distribution-And-Licensing.md, line 14 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWU_62gDP4MNY-mo5rI:-MWU_62h7TCF3Rf4wya3:bbddqcz) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Distribution-And-Licensing.md#L14)):*
> ```Markdown
> > **IMPORTANT:** It is the responsibility of the end users who build the OpenMPF software to abide by all of the non-commercial and re-distribution restrictions imposed by the dependencies that the OpenMPF software uses. Building OpenMPF and linking in these dependencies at build time or run time may result in creating a derivative work under the terms of the GNU General Public License. Refer to [Acknowledgements](Acknowledgements/index.html) for more information about these dependencies.
> 
> In general, it is only acceptable to use and distribute the executable form of the OpenMPF, which includes generated Docker images, "in house", which is loosely defined as internally with an organization. The OpenMPF should only be distributed to third parties in raw source code form and those parties will be responsible for creating their own executables and Docker images.
> ```

This whole section is confusing because we do provide compiled versions on Dockerhub.
___
*[docs/docs/Install-Guide.md, line 5 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWUaYC26bwL61HMU93w:-MWUaYC26bwL61HMU93x:b4qtyqz) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Install-Guide.md#L5)):*
> ```Markdown
> # Docker
> 
> OpenMPF is installed using the Docker container platform. Please read the [disclaimer](#disclaimer) below.
> ```

The referenced disclaimer is gone.

**Comment by jrobble** [comment]
___
*[docs/docs/Distribution-And-Licensing.md, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWUXltw94mJO2VkVaFv:-MWVWDso8WofBoudOiKD:bhw1s2y) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Distribution-And-Licensing.md#L8)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't know why you do this to yourself. You can wrap long lines. 

These two produce identical output:
```
This is sample text. This is more text.

This is another paragraph.
```


```
This is 
sample text. 
This is 
more 
text.

This is another 
paragraph.
```

</blockquote></details>

The disclaimer is copied from what's on DockerHub. I didn't bother to add newlines before. I just reflowed it in Atom.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/125)* status: 1 of 55 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/Distribution-And-Licensing.md, line 14 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWU_62gDP4MNY-mo5rI:-MWVZm8ZCCQcFMJUFrzj:bu4h0uv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Distribution-And-Licensing.md#L14)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This whole section is confusing because we do provide compiled versions on Dockerhub.
</blockquote></details>

I agree. That part is a carry-over from before Docker. I removed a lot of it.
___
*[docs/docs/Install-Guide.md, line 5 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWUaYC26bwL61HMU93w:-MWV_O6NExYdApYvj-Qo:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Install-Guide.md#L5)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The referenced disclaimer is gone.
</blockquote></details>

Done.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 2 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/125)* status: 2 of 55 files reviewed, all discussions resolved (waiting on @jrobble)

___
*[docs/docs/Distribution-And-Licensing.md, line 8 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/125#-MWUXltw94mJO2VkVaFv:-MW_4hy_9VxxDRAFI4QR:b-73z1ek) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/ec3d29c107ef675579a256ce8b65613a05169f16/docs/docs/Distribution-And-Licensing.md#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The disclaimer is copied from what's on DockerHub. I didn't bother to add newlines before. I just reflowed it in Atom.
</blockquote></details>

I meant that as a "for future reference" thing.

**Pull request merged**
