### PR TITLE
Add JsonMediaRange

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1283

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1439

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/138)

### CODE REVIEW

**Review by clnowacki — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/138)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/138#-Mr8NrCW1TBGhmwSUHms:-Mr8NrCW1TBGhmwSUHmt:b-y05nea) (no related file):*
Please generate the site. Specifically, ensure that `/docs/site/html/REST-API.html` is updated.

---

Also, the numbering is off. Specifically,

```
1. Definitions
   3.1. EnvironmentVariableModel
```

```
2. Paths
   4.1. GET  /rest/info
```

That used to be:

```
1. Definitions
   1.1. EnvironmentVariableModel
```

```
2. Paths
   2.1. GET  /rest/info
```

---

There are two numbers in these places:

```
3.5 1.5. JobCreationMediaData
```

```
3.7 1.6. DeployedServiceModel (Response only)
```

---

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/138)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @clnowacki, and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/138#-Mr8NrCW1TBGhmwSUHms:-Mr8We9Q4Db_qljER0Pc:bpcn77e) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please generate the site. Specifically, ensure that `/docs/site/html/REST-API.html` is updated.

---

Also, the numbering is off. Specifically,

```
1. Definitions
   3.1. EnvironmentVariableModel
```

```
2. Paths
   4.1. GET  /rest/info
```

That used to be:

```
1. Definitions
   1.1. EnvironmentVariableModel
```

```
2. Paths
   2.1. GET  /rest/info
```

---

There are two numbers in these places:

```
3.5 1.5. JobCreationMediaData
```

```
3.7 1.6. DeployedServiceModel (Response only)
```
</blockquote></details>

Done.

The numbering issue only appeared in Firefox

---

**Review by jrobble — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
