### PR TITLE
removed references to DLib, OcvPerson, and Darknet components

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1350

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1388
- https://github.com/openmpf/openmpf-components/pull/272
- https://github.com/openmpf/openmpf-contrib-components/pull/74
- https://github.com/openmpf/openmpf-docker/pull/150

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: all files reviewed, 5 unresolved discussions (waiting on @clnowacki)

___
*[docs/docs/GPU-Support-Guide.md, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-Mib_ykHD22KESiJHS5E:-Mib_ykHD22KESiJHS5F:butzwcq) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/GPU-Support-Guide.md#L36)):*
> ```Markdown
> to provide maximum runtime portability. For any new components that may be developed, this may not be the case, and
> similar testing should be undertaken to determine the correct set of flags for that component. The nvcc compiler flags
> are configured by setting the `CUDA_NVCC_FLAGS` CMake variable in the individual component's CMakeLists.txt file, e.g.,
> ```

Let's use a colon like `e.g.:`.
___
*[docs/docs/GPU-Support-Guide.md, line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibaTHiBDLKZnABqhe_:-MibaTHiBDLKZnABqhea:b1oi284) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/GPU-Support-Guide.md#L48)):*
> ```Markdown
> 
> 
> > **NOTE:** OpenMPF GPU components are written so that they can run on the CPU only, as well as using GPU hardware. 
> ```

Let's be forward-leaning and preface this with "Most OpenMPF GPU components".
___
*[docs/docs/User-Guide.md, line 179 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-Mibb-4150OY_ieyhAnP:-Mibb-4150OY_ieyhAnQ:bd8greq) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/User-Guide.md#L179)):*
> ```Markdown
> Job Statistics Page
> 
> For example, the OCV YOLO OBJECT DETECTION PIPELINE was run once. Note that the Y-axis in the bar graph has a logarithmic scale. Hovering the mouse over any bar in the graph will show more information. Information about each pipeline is listed below the graph.
> ```

I see that you replaced the stats image for this doc. There are still a lot of other images that mention old components and pipelines here and in the Admin Guide. Unless we want to change them all (which I don't think is necessary), I think you should leave the image and content the same and just add a banner to the top of the page:

```
<div style="background-color:DeepSkyBlue"><p style="color:white; padding:5px"><b>INFO:</b> This document describes components and pipelines that are no longer supported by OpenMPF; however, the images and general content still reflect the appearance and usage of the OpenMPF web UI and its features.</p></div>
```

The same banner should be added to the Admin Guide.

That way we're also covered for any future changes to the components and pipelines.
___
*[docs/docs/html/REST-API.html, line 2308 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibeHDk8-l_29yhuydV:-MibeHDk8-l_29yhuydW:b66838j) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/html/REST-API.html#L2308)):*
> ```HTML
>                                                         <td class="td-alignment-std"><b>JsonOutputObject</b> example:
>                                                             <br>
>                                                             <pre style="color: rgb(0, 0, 0); background-color: #ECECB4;">
> ```

When you make a change to this doc you should update the `Last updated on:` string. 

FYI, the `Version 6.2.5` string should only be updated when there is an API change, and it should be updated to the current version of OpenMPF (similarly to how we only tag GitHub repos when there is a change).
___
*[docs/docs/html/REST-API.html, line 2315 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibgLGEA4VVStR_tE4p:-MibgLGEA4VVStR_tE4q:b-bk905z) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/html/REST-API.html#L2315)):*
> ```HTML
>   "objectId": "eccdf7ae-f24c-496f-97fd-ad653f05703e",
>   "pipeline": {
>     "name": "OCV FACE DETECTION PIPELINE",
> ```

When we originally created this example the goal was to try to provide output that would cover parallel actions and no tracks cases.

In retrospect, I think parallel actions may be a bit much to include here. We should probably keep it simple, as you've done. Also, parallel actions aren't used very much in practice. I still think we should have a NO TRACKS output.

I like how your example shows the output for multiple pieces of media, but I think it's longer than it needs to be and we can shorten it to just two pieces of media. I think we should show the results of one piece of media that generates the track, and another piece of media that generates NO TRACKS.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: all files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/GPU-Support-Guide.md, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-Mib_ykHD22KESiJHS5E:-Mj0PcKU9b8nvzzLTDOQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/GPU-Support-Guide.md#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's use a colon like `e.g.:`.
</blockquote></details>

Done.
___
*[docs/docs/GPU-Support-Guide.md, line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibaTHiBDLKZnABqhe_:-Mj0Pj7pA3ozm3bwiISZ:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/GPU-Support-Guide.md#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's be forward-leaning and preface this with "Most OpenMPF GPU components".
</blockquote></details>

Done.
___
*[docs/docs/User-Guide.md, line 179 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-Mibb-4150OY_ieyhAnP:-Mj0giLmECeKu-Vl2dNi:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/User-Guide.md#L179)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I see that you replaced the stats image for this doc. There are still a lot of other images that mention old components and pipelines here and in the Admin Guide. Unless we want to change them all (which I don't think is necessary), I think you should leave the image and content the same and just add a banner to the top of the page:

```
<div style="background-color:DeepSkyBlue"><p style="color:white; padding:5px"><b>INFO:</b> This document describes components and pipelines that are no longer supported by OpenMPF; however, the images and general content still reflect the appearance and usage of the OpenMPF web UI and its features.</p></div>
```

The same banner should be added to the Admin Guide.

That way we're also covered for any future changes to the components and pipelines.
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 2308 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibeHDk8-l_29yhuydV:-Mj0jL5V7eJ5vZhg8JNr:bq9z4tk) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/html/REST-API.html#L2308)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When you make a change to this doc you should update the `Last updated on:` string. 

FYI, the `Version 6.2.5` string should only be updated when there is an API change, and it should be updated to the current version of OpenMPF (similarly to how we only tag GitHub repos when there is a change).
</blockquote></details>

I'm confused by your comment. I did not change the Version 6.2.5 string in this document. Are you simply informing me of that, or did you need me to do something?
___
*[docs/docs/html/REST-API.html, line 2315 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibgLGEA4VVStR_tE4p:-Mj13OoiEI29XpGI0ZN7:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/html/REST-API.html#L2315)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When we originally created this example the goal was to try to provide output that would cover parallel actions and no tracks cases.

In retrospect, I think parallel actions may be a bit much to include here. We should probably keep it simple, as you've done. Also, parallel actions aren't used very much in practice. I still think we should have a NO TRACKS output.

I like how your example shows the output for multiple pieces of media, but I think it's longer than it needs to be and we can shorten it to just two pieces of media. I think we should show the results of one piece of media that generates the track, and another piece of media that generates NO TRACKS.
</blockquote></details>

Done.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: 4 of 17 files reviewed, 5 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[docs/docs/html/REST-API.html, line 2308 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MibeHDk8-l_29yhuydV:-Mj4iOcp-22krCfRCNxG:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a2354cb27f30173d5dea9657bc13780916f7ec7e/docs/docs/html/REST-API.html#L2308)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm just informing you about `Version 6.2.5`, but I am asking you to update the `Last updated on:` string.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: all files reviewed, 1 unresolved discussion (waiting on @clnowacki)

___
*[docs/docs/html/REST-API.html, line 2345 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MjAyKmt9dIvk0RQmZum:-MjAyKmt9dIvk0RQmZun:bg5bn7m) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/52bd2b9541dba6e609c3039a4321ccccb53327e2/docs/docs/html/REST-API.html#L2345)):*
> ```HTML
>     {
>       "mediaId": 3,
>       "path": "file:///opt/mpf/share/remote-media/girl-1741925_1920.jpg",
> ```

Maybe we should call this `girls-1741925_1920.jpg` (notice the plural "girls") since there are two tracks. I'm not sure what the tracks actually contain, but from an uninformed reader's POV I would expect one face from a media file called `girl`.

**Comment by jrobble** [comment]
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MjB106e65abmQW82V33:-MiblDyo2Rj1SaRNy8ew:b-6v74ni) (no related file):*
As mentioned in the other PR:

> I think we should move this file out of the openmpf repo and into openmpf-build-tools/config-files/openmpf-example-package.json (making sure to update the links in the Development Environment Guide).

`Development-Environment-Guide.md` links to `/home/mpf/openmpf-projects/openmpf/trunk/jenkins/scripts/config_files/openmpf-open-source-package.json` twice. Please update those links.

---

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: all files reviewed, 2 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MjB106e65abmQW82V33:-MjFPmej9ExWndGxAeCC:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As mentioned in the other PR:

> I think we should move this file out of the openmpf repo and into openmpf-build-tools/config-files/openmpf-example-package.json (making sure to update the links in the Development Environment Guide).

`Development-Environment-Guide.md` links to `/home/mpf/openmpf-projects/openmpf/trunk/jenkins/scripts/config_files/openmpf-open-source-package.json` twice. Please update those links.
</blockquote></details>

Done.

---
___
*[docs/docs/html/REST-API.html, line 2345 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/135#-MjAyKmt9dIvk0RQmZum:-MjEyTxO7VykAm9M0k9P:b-v3zv25) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/52bd2b9541dba6e609c3039a4321ccccb53327e2/docs/docs/html/REST-API.html#L2345)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Maybe we should call this `girls-1741925_1920.jpg` (notice the plural "girls") since there are two tracks. I'm not sure what the tracks actually contain, but from an uninformed reader's POV I would expect one face from a media file called `girl`.
</blockquote></details>

I changed it to "faces.jpg"

**Review by jrobble — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Pull request merged**
