### PR TITLE
feature/cli-runner - Update logging info in C++ and Python SDK docs.

### PR DESCRIPTION
**Pull request by brosenberg42**
Issue: https://github.com/openmpf/openmpf/issues/1003
Associated PRs:
- https://github.com/openmpf/openmpf/pull/1168
- https://github.com/openmpf/openmpf-components/pull/183
- https://github.com/openmpf/openmpf-contrib-components/pull/64
- https://github.com/openmpf/openmpf-docker/pull/118
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/90
- https://github.com/openmpf/openmpf-python-component-sdk/pull/27
- https://github.com/openmpf/openmpf.github.io/pull/120

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Python-Batch-Component-API.md, line 1168 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAU0UW2El0PllkvV2N:-MNAU0UW2El0PllkvV2O:b-rlrycw) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Python-Batch-Component-API.md#L1168)):*
> ```Markdown
> same component can log to the same file. Also, logging content can span multiple lines. 
> 
> The following log levels are supported: `FATAL, ERROR, WARN, INFO, DEBUG`. 
> ```

I'm looking at [this table](https://docs.python.org/3/library/logging.html#levels). Of note, I see `WARNING` and `CRITICAL`, which are different from the `WARN` and `FATAL` values listed above.

I see you remap `WARN` and `FATAL` here:

```
    logging.addLevelName(logging.WARN, 'WARN')
    # Change default level name for logger.fatal and logger.critical from 'CRITICAL' to 'FATAL'
    logging.addLevelName(logging.FATAL, 'FATAL')
```

It may be worth mentioning this remapping here in the doc if Python developers are thrown off by using different names for things they're accustomed to. 
___
*[docs/docs/Release-Notes.md, line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAaHtp0xr9uS_pjV84:-MNAaHtqADXygBa4046x:b-mcgrl3) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L3)):*
> ```Markdown
> > **NOTICE:** This software (or technical data) was produced for the U.S. Government under contract, and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV (DEC 2007). Copyright 2020 The MITRE Corporation. All Rights Reserved.
> 
> # OpenMPF 5.1.0: XXX 2020
> ```

Please merge with develop and put your new entries in an "OpenMPF TBD: XXX" section instead.

I don't want to commit to the next release being 5.2.0, or being released in 2020. Best to be as vague as possible here. There is a possibility that the next numbered release will for 6.0.0, for example, depending on how priorities might change.
___
*[docs/docs/Release-Notes.md, line 9 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAbRsX9P1TzQjHO9LH:-MNAbRsY81U2zMpBALuX:b-86tk1c) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L9)):*
> ```Markdown
> - <span style="color:red">TODO: This new component detects objects in images and videos by making use of an [NVIDIA TensorRT Inference Server](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/) (TRTIS), and calculates features that can later be used by other systems to recognize the same object in other media. We provide support for running the server as a separate service during a Docker deployment, but an external server instance can be used instead. By default, the ip_irv2_coco model is supported and will optionally classify detected objects using [COCO labels](https://github.com/openmpf/openmpf-components/blob/master/cpp/trtisdetection/plugin-files/models/ip_irv2_coco.labels). Additionally, features can be generated for whole frames, automatically-detected object regions, and user-specified regions. Refer to the [README](https://github.com/openmpf/openmpf-components/blob/master/cpp/trtisdetection/README.md).</span>
> 
> ## C++ Batch Component API ##
> ```

Instead of `## ` use `<h2>` for this sub-section and the two below, like the rest of the doc. This prevents these sections from appearing in the sidebar on the right.
___
*[docs/docs/Release-Notes.md, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAcSQI6Pp27JmBBTl9:-MNAcSQI6Pp27JmBBTlA:bfo4mra) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L30)):*
> ```Markdown
>   `COMPONENT_LOG_NAME` environment variable in their Dockerfiles.
> 
> - Component images now support running the component on the command line. See the 
> ```

This last bullet is most important to an uninitiated reader and should be in a separate sub-section called "OpenMPF Command Line Runner" that appears before the other sub-sections.  That way we introduce the feature before getting into the details of code changes made to support it.

In the new sub-section, minimally, please mention that the new feature enables individual components to be run persistently, or as a one-shot, as Docker containers to process individual pieces of media and provide the results in a the format of a JSON output object. The effect is similar to a single-stage pipeline. Also, mention which components are supported.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Python-Batch-Component-API.md, line 321 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MQsHMnl4DtnqakJsBar:-MQsHMnm7n-0RRxCcQAU:bjvy3mr) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Python-Batch-Component-API.md#L321)):*
> ```Markdown
> import mpf_component_api as mpf
> 
> logger = mpf.configure_logging('my-component.log', __name__ == '__main__')
> ```

As stated in the update you made to the Release Notes, this line should be changed to use `logging.getLogger(...)`.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Release-Notes.md, line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MVYI-QY9Pr-3JzFga-n:-MVYI-QY9Pr-3JzFga-o:b-hwyjcs) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L3)):*
> ```Markdown
> > **NOTICE:** This software (or technical data) was produced for the U.S. Government under contract, and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV (DEC 2007). Copyright 2020 The MITRE Corporation. All Rights Reserved.
> 
> # OpenMPF 5.1.0: XXX 2020
> ```

Also, please add a section to the release notes that describes the changes you made to the Python component base images.

**Review by jrobble — COMMENTED** [review]
Give a brief description of the CLI Runner behavior, and link to `cli-runner/README.md` from the User Guide.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-:-MWfBVX363q0l-dWfcu_:b7sg8xa)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: all files reviewed, 6 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/Python-Batch-Component-API.md, line 321 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MQsHMnl4DtnqakJsBar:-MWej3c327dIUy8nvxzB:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Python-Batch-Component-API.md#L321)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As stated in the update you made to the Release Notes, this line should be changed to use `logging.getLogger(...)`.
</blockquote></details>

Done.
___
*[docs/docs/Python-Batch-Component-API.md, line 1168 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAU0UW2El0PllkvV2N:-MWemowi1_5jfLUI--ZJ:b-i78xs3) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Python-Batch-Component-API.md#L1168)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm looking at [this table](https://docs.python.org/3/library/logging.html#levels). Of note, I see `WARNING` and `CRITICAL`, which are different from the `WARN` and `FATAL` values listed above.

I see you remap `WARN` and `FATAL` here:

```
    logging.addLevelName(logging.WARN, 'WARN')
    # Change default level name for logger.fatal and logger.critical from 'CRITICAL' to 'FATAL'
    logging.addLevelName(logging.FATAL, 'FATAL')
```

It may be worth mentioning this remapping here in the doc if Python developers are thrown off by using different names for things they're accustomed to. 
</blockquote></details>

Python accepts WARN or WARNING. By default, when the log messages are formatted "WARNING" appears. That code changes it to "WARN". The same thing applies to FATAL and CRITICAL. I think it is better to just make the code accept either.
___
*[docs/docs/Release-Notes.md, line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAaHtp0xr9uS_pjV84:-MWeSzcADtfDFB5FoIaj:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please merge with develop and put your new entries in an "OpenMPF TBD: XXX" section instead.

I don't want to commit to the next release being 5.2.0, or being released in 2020. Best to be as vague as possible here. There is a possibility that the next numbered release will for 6.0.0, for example, depending on how priorities might change.
</blockquote></details>

Done.
___
*[docs/docs/Release-Notes.md, line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MVYI-QY9Pr-3JzFga-n:-MWeXCt-C3jTdMNunjTr:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, please add a section to the release notes that describes the changes you made to the Python component base images.
</blockquote></details>

Done.
___
*[docs/docs/Release-Notes.md, line 9 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAbRsX9P1TzQjHO9LH:-MWeWj0-0nePVYfBrxod:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L9)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of `## ` use `<h2>` for this sub-section and the two below, like the rest of the doc. This prevents these sections from appearing in the sidebar on the right.
</blockquote></details>

Done.
___
*[docs/docs/Release-Notes.md, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAcSQI6Pp27JmBBTl9:-MWeXSvy9E_oV1_d5-Vu:bx539g3) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L30)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This last bullet is most important to an uninitiated reader and should be in a separate sub-section called "OpenMPF Command Line Runner" that appears before the other sub-sections.  That way we introduce the feature before getting into the details of code changes made to support it.

In the new sub-section, minimally, please mention that the new feature enables individual components to be run persistently, or as a one-shot, as Docker containers to process individual pieces of media and provide the results in a the format of a JSON output object. The effect is similar to a single-stage pipeline. Also, mention which components are supported.
</blockquote></details>

I don't think we really need to duplicate information between this and the README. A link should be sufficient, but I was going to just paraphrase what you had there. Then, I read it more closely and I think it is confusing. It sounds like the new behavior is that component containers now be configured to exit after processing a single piece of media. We already have Docker containers that run single components. The existing components receive jobs that instruct them to process an individual piece of media. The component output does eventually become a JSON output object.

I don't think "persistently" is the right word here. If we are going to add a brief summary, I don't think the `docker run` vs `docker exec` behavior is even important enough to go there.

**Review by jrobble — CHANGES_REQUESTED** [review]
Specifically, I think we should add the following paragraph right at the beginning of the User Guide under "General", above "Accessing the Web UI", which states:

> The Open Media Processing Framework (OpenMPF) can be used in three ways:
>
> - Through the OpenMPF Web user interface (UI)
> - Through the REST API endpoints (Provide link to "REST API" within the User Guide. Within that section please  update "various REST API endpoints" to link to the actual REST API doc.)
> - Through the CLI Runner (Provide link to CLI Runner readme.)
>
> This guide will focus on using the OpenMPF Web UI.

We will no longer need to define the OpenMPF and UI acronyms in the "Accessing the Web UI" section.

---

Also, I think the "Detection Chaining" section and everything underneath it should be split out into a new doc called "Pipeline and Video Segments Guide", and the "Segmenting Media" section of that doc should link to the "Feed Forward Guide", but I know that's tangential to your task.

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-:-MWkIScqA4UVUfb2BG5P:bas9gy6)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[docs/docs/Release-Notes.md, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MNAcSQI6Pp27JmBBTl9:-MWkIL6NAsihuo_Ii6Pz:b-e61rc0) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/832387881a4873909c78c97493d2e48ca129762a/docs/docs/Release-Notes.md#L30)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think we really need to duplicate information between this and the README. A link should be sufficient, but I was going to just paraphrase what you had there. Then, I read it more closely and I think it is confusing. It sounds like the new behavior is that component containers now be configured to exit after processing a single piece of media. We already have Docker containers that run single components. The existing components receive jobs that instruct them to process an individual piece of media. The component output does eventually become a JSON output object.

I don't think "persistently" is the right word here. If we are going to add a brief summary, I don't think the `docker run` vs `docker exec` behavior is even important enough to go there.


</blockquote></details>

I think what you have is good.
___
*[docs/docs/Release-Notes.md, line 37 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MWkGSeuAbXUzqPcpf3-:-MWkGSeuAbXUzqPcpf30:b-mkaanh) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/b94399bdee802fa6db99d5607b9e74ba12b0eff3/docs/docs/Release-Notes.md#L37)):*
> ```Markdown
> 
> - Added the 
>   [`openmpf_python_executor_ssb` base image](https://github.com/openmpf/openmpf-docker/blob/master/components/python/README.md). 
> ```

Please link to the specific section:

https://github.com/openmpf/openmpf-docker/blob/master/components/python/README.md#openmpf_python_executor_ssb

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/Release-Notes.md, line 37 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/120#-MWkGSeuAbXUzqPcpf3-:-MWy0PDf2arl0VMmHIUj:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/b94399bdee802fa6db99d5607b9e74ba12b0eff3/docs/docs/Release-Notes.md#L37)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please link to the specific section:

https://github.com/openmpf/openmpf-docker/blob/master/components/python/README.md#openmpf_python_executor_ssb
</blockquote></details>

Done.

**Review by jrobble — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
