### PR TITLE
Feat/check tiesdb

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1613
- https://github.com/openmpf/openmpf/issues/1438

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1614

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 8 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZsTYYDYjFlyNoBTZb:-NRZsTYZ5gcDaHBBn3HR:b-s9xj36) (no related file):*
Overall, this is very good. As for structure, I suggest making the part where you explain the `data.ties.db.check.ignorable.properties.file` a sub-section of "Before Job Check" (which will help when you link to it from the "Configuration" section - see my other comment) and also the part where you explain providing the media hash and mime type a sub-section of "Before Job Check".

___
___
*[`docs/docs/TiesDb-Guide.md` line 13 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZlsbFAf3bWXm2Y_Xh:-NRZlsbG-n2ETHxBihDC:b-eyd025) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L13)):*
> ```Markdown
> "assertion", which is used to represent metadata about the media object. In our case it
> represents the detection and track information in the OpenMPF JSON output object. Workflow Manager
> can be configured to check TiesDb for a supplemental it previously created and use the results
> ```

Please also explain that we choose the most recently created supplementals first, and also that we prioritize `COMPLETE` over `COMPLETE_WITH_WARNINGS`, and `COMPLETE_WITH_WARNINGS` is prioritized over `COMPLETE_WITH_ERRRORS`.
___
*[`docs/docs/TiesDb-Guide.md` line 18 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZlNau7-tgBjZlSHYS:-NRZlNau7-tgBjZlSHYT:bt30k1w) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L18)):*
> ```Markdown
> 
> # Configuration
> - `TIES_DB_URL` job property or `ties.db.url` system property
> ```

Provide an example URL.
___
*[`docs/docs/TiesDb-Guide.md` line 24 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZmIm12rXF3KZ30W-l:-NRZmIm12rXF3KZ30W-m:b7o9n44) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L24)):*
> ```Markdown
> - `TIES_DB_S3_COPY_DISABLED` job property or `ties.db.s3.copy.disabled` system property
>     - When true and a job is skipped because a compatible job is found in TiesDb, the results
>       from the previous job will not be copied to a different S3 bucket.
> ```

Please explain in a paragraph in the overview section how S3 object storage works with TiesDb. Specifically:

- How we copy the artifacts, markup, and derivative media from the old job into the S3 bucket configured for the new job, if the S3 bucket is different.
- How we create a new JSON output object with `tiesDbSourceJobId` set when we copy to a new S3 bucket, and how `tiesDbSourceJobId` is not set if we don't do the copy.
   - Also how the URLs are updated in the new JSON output object.
___
*[`docs/docs/TiesDb-Guide.md` line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZoSoDDYFKLuk2_Qio:-NRZoSoG4MHSjLRaxTji:bvvjbxp) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L57)):*
> ```Markdown
> - `data.ties.db.check.ignorable.properties.file` system property
>     - Path to the JSON file containing the list of properties that should not be considered when
>       checking for a compatible job in TiesDb.
> ```

Refer the reader (with link) to the appropriate section below for what this file looks like.
___
*[`docs/docs/TiesDb-Guide.md` line 65 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZtuFp2rS7GEG0SMTi:-NRZtuFq8bCAaDIRRu8N:b-ttrpiv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L65)):*
> ```Markdown
> Workflow Manager will post a supplemental to the provided URL.
> 
> This is an example of what Workflow Manager will post to TiesDb:
> ```

Please mention an example of the TiesDb URL with path and parameters where this will be posted.
___
*[`docs/docs/TiesDb-Guide.md` line 104 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZotodCbnxamCbCN1m:-NRZotoe8I0dkfd_V_vn:b-14euh1) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L104)):*
> ```Markdown
> In order to determine if a previous job was similar enough to a current job, a hash of the
> important parts of the jobs is computed. There are certain job properties, that when changed, do
> not change the output. There are also job properties that only affect certain types of media. To
> ```

Other than the common properties and algorithm properties, which you do a good job explaining here, please list out the other values that are used in computing the job hash, namely:

- JSON output object version
- `output.changed.counter`
- Algorithm output version
- Frame ranges and time ranges

Please explain how the `output.changed.counter` and Algorithm output version are essentially counters used to invalidate old TiesDb records and will be incremented whenever a WFM or algorithm update is made that should require jobs to be re-run.

---

Please explain that a record in TiesDb represents all media for a job run and that in order for the hash of a later job run to match the previous run, the later run must be configured with all of the same media. This is acceptable because when using TiesDb because usually only one piece of media is run per job.
___
*[`docs/docs/TiesDb-Guide.md` line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRZqrg70kJTdY3Ww4Rg:-NRZqrg70kJTdY3Ww4Rh:bz1mrqu) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/5d78b5b8d77194f388bf0aceed98ef26643b979b/docs/docs/TiesDb-Guide.md#L114)):*
> ```Markdown
> to ignore the properties listed in the `names` list.
> 
> In the example below, the `"VERBOSE"` job property is never included in the job hash because all
> ```

No need for quotes around `VERBOSE`, `ARTIFACT_EXTRACTION_POLICY`, and `FRAME_INTERVAL` since you formatted them as code.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/site/TiesDb-Guide/index.html` line 462 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRhwLLiAylbaQW-tcZs:-NRhwLLj45BWrip29ESe:b-oot804) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/6c11759a4410af9c46683b4848398fe3ec498092/docs/site/TiesDb-Guide/index.html#L462)):*
> ```HTML
> the values from the current job and apply to the destination of the copy. If the values for the
> S3 properties should be different for the source of the copy, the properties prefixed with
> <code>TIES_DB_COPY_SRC_</code> can be set. If for a given property the <code>TIES_DB_COPY_SRC_</code> prefixed version is
> ```

I think it would be best to link to the Object Storage Guide in here somewhere.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 31 of 36 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/site/TiesDb-Guide/index.html` line 462 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRhwLLiAylbaQW-tcZs:-NRiAZDUDqNSnqFaxV0v:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/6c11759a4410af9c46683b4848398fe3ec498092/docs/site/TiesDb-Guide/index.html#L462)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think it would be best to link to the Object Storage Guide in here somewhere.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/site/TiesDb-Guide/index.html` line 462 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRhwLLiAylbaQW-tcZs:-NRiccWjCKADqIKLSTCB:b-95g85j) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/6c11759a4410af9c46683b4848398fe3ec498092/docs/site/TiesDb-Guide/index.html#L462)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think linking to it once is sufficient. I think we should remove the second link. As a reader, I would assume these link me to different places since there's no need to have two links in the same paragraph to the same place.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 32 of 36 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/site/TiesDb-Guide/index.html` line 462 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRhwLLiAylbaQW-tcZs:-NRieCvh0VH4Ed1kBCqf:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/6c11759a4410af9c46683b4848398fe3ec498092/docs/site/TiesDb-Guide/index.html#L462)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think linking to it once is sufficient. I think we should remove the second link. As a reader, I would assume these link me to different places since there's no need to have two links in the same paragraph to the same place.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsb9Ch3h9iENJVqO-b:-NRsb9Ch3h9iENJVqO-c:b-5pm8fj) (no related file):*
Please update Component Descriptor Reference with `outputVersion`, which I propose changing to `outputChangedCounter` to match the WFM's `output.changed.counter`.

___
___
*[`docs/docs/html/REST-API.html` line 173 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdKIV-8XSr8qkoKo-:-NRsdKIW0qrP_8GX1am1:bh1x5y) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L173)):*
> ```HTML
>     <div style='page-break-after:always'>
>         <h1>OpenMPF Workflow Manager REST API</h1>
>         <h2>Version 7.0.0</h2>
> ```

Update this version.
___
*[`docs/docs/html/REST-API.html` line 182 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdTv_BviwrCKDDURQ:-NRsdTv_BviwrCKDDURR:b-sotmk8) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L182)):*
> ```HTML
>         </font></i></p>
>         <p><i><font size="3">
>             Copyright 2022 The MITRE Corporation. All Rights Reserved.
> ```

Update the copyright.
___
*[`docs/docs/html/REST-API.html` line 186 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdNP3DX72MriP7vJN:-NRsdNP6Ccpgx2kvyjhj:bf4ygds) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L186)):*
> ```HTML
>         <br/>
>     </div>
>     <div class='footer'>Last updated on: February 21, 2022</div>
> ```

Update this date.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 30 of 37 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsb9Ch3h9iENJVqO-b:-NS5zyf56vE2O9C6g78Q:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update Component Descriptor Reference with `outputVersion`, which I propose changing to `outputChangedCounter` to match the WFM's `output.changed.counter`.
</blockquote></details>

Done.

___
___
*[`docs/docs/html/REST-API.html` line 173 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdKIV-8XSr8qkoKo-:-NS5rgwn94CTlkKb8J86:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L173)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update this version.
</blockquote></details>

Done.
___
*[`docs/docs/html/REST-API.html` line 182 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdTv_BviwrCKDDURQ:-NS5rhb4ApE752ugLunF:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L182)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update the copyright.
</blockquote></details>

Done.
___
*[`docs/docs/html/REST-API.html` line 186 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NRsdNP3DX72MriP7vJN:-NS5rmwD5bKAgD-dEOZJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ef5cffd9f6eba17c3bac008344665dd46ddbc92/docs/docs/html/REST-API.html#L186)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update this date.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/docs/TiesDb-Guide.md` line 128 at r5](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NS7c4kICFjQRqChZR6i:-NS7c4kICFjQRqChZR6j:b-we4k53) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1ff8837d5f9ef30c51a870dfb29f52f153c6b892/docs/docs/TiesDb-Guide.md#L128)):*
> ```Markdown
>       which previous TiesDb records should not be used. Because this number is part of the job
>       configuration hash, changing this number invalidates all previous TiesDb records.
> - Component descriptor's `outputVersion` property.
> ```

Change this to `outputChangedCounter`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 32 of 37 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/docs/TiesDb-Guide.md` line 128 at r5](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NS7c4kICFjQRqChZR6i:-NSAw8QZ1VK1cdxvnelw:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1ff8837d5f9ef30c51a870dfb29f52f153c6b892/docs/docs/TiesDb-Guide.md#L128)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change this to `outputChangedCounter`.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgo3Xa1c9be-IIrhGa:-NSgo3Xa1c9be-IIrhGb:b-qkxivj) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
> ```Markdown
> then, when accessing the previous job's results `access-key` will be used for the access key and
> `old-secret-key` will be used for the secret key. When uploading the results to the new bucket,
> `access-key` will be used for the access key and `new-secret-key` will be used for the secret key.
> ```

Please explain that copying results will always result in a new JSON output object, even if using the same S3 location as the previous job, and that if the same S3 location is used then a copy of the artifacts, markup, and derivative media are not created.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NSgrjJq5csMWM4_OIJO:bcx01t8) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
> ```Markdown
> then, when accessing the previous job's results `access-key` will be used for the access key and
> `old-secret-key` will be used for the secret key. When uploading the results to the new bucket,
> `access-key` will be used for the access key and `new-secret-key` will be used for the secret key.
> ```

Regarding the behavior when only using local file storage, I feel like we should explain somewhere in this doc how that works since it does not result in creating a copy of the JSON output object.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 32 of 37 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NSk1XDlE1C0k9oWwa27:b-b4xckb) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Regarding the behavior when only using local file storage, I feel like we should explain somewhere in this doc how that works since it does not result in creating a copy of the JSON output object.
</blockquote></details>

When the S3 copy is enabled, a new output object is created regardless of where the source content is stored.
___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgo3Xa1c9be-IIrhGa:-NSk7SOTDyim-4iifWyj:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please explain that copying results will always result in a new JSON output object, even if using the same S3 location as the previous job, and that if the same S3 location is used then a copy of the artifacts, markup, and derivative media are not created.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: 32 of 37 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NSrSy1S4YNleBHDu46U:b-yevniv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

When the S3 copy is enabled, a new output object is created regardless of where the source content is stored.
</blockquote></details>

I'm saying we should explain the behavior when no S3 properties are specified at all. A user is not going to think that `TIES_DB_S3_COPY_ENABLED` has any relevance in that case. If it does, we should explain that.

**Review by jrobble — COMMENTED** [review]
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NTExhvz-fQ4R331K2nN:bj98nl6) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm saying we should explain the behavior when no S3 properties are specified at all. A user is not going to think that `TIES_DB_S3_COPY_ENABLED` has any relevance in that case. If it does, we should explain that.
</blockquote></details>

That is the case. `TIES_DB_S3_COPY_ENABLED` has no relevance.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NTFBUXC6ly07VD2yF9w:br8eef3) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
Yeah, I'm not being clear. If you look at the doc as a whole, we talk about how the JSON is generated when using S3 object storage, but not otherwise. I agree that the non-S3 behavior should not be part of the "S3 Copy" section.

In the `Before Job Check` section we say:

> Workflow Manager will use the output of the previous job to create the output for the current job.

The confusing part here is "create the output" which implies creating a new JSON output object.

I propose that we update that to:

> Workflow Manager will use the output of the previous job for the current job. In setups that don't use S3 object storage, the old JSON output object will be reused. No new JSON output object will be created. When S3 object storage is used, Workflow Manager will attempt to create a new JSON output object using the content of the previous job. Workflow Manager can be configured to copy the results of the previous job to a different S3 bucket. In cases where they copy fails, a link to the old JSON output object will be provided.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/docs/TiesDb-Guide.md` line 231 at r6](https://reviewable.io/reviews/openmpf/openmpf.github.io/163#-NSgrjJq5csMWM4_OIJN:-NTFXy9l7tus4lt_10ss:b-yuhnqu) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2d5b0986957a8467e9c549cce27d345fc196e373/docs/docs/TiesDb-Guide.md#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yeah, I'm not being clear. If you look at the doc as a whole, we talk about how the JSON is generated when using S3 object storage, but not otherwise. I agree that the non-S3 behavior should not be part of the "S3 Copy" section.

In the `Before Job Check` section we say:

> Workflow Manager will use the output of the previous job to create the output for the current job.

The confusing part here is "create the output" which implies creating a new JSON output object.

I propose that we update that to:

> Workflow Manager will use the output of the previous job for the current job. In setups that don't use S3 object storage, the old JSON output object will be reused. No new JSON output object will be created. When S3 object storage is used, Workflow Manager will attempt to create a new JSON output object using the content of the previous job. Workflow Manager can be configured to copy the results of the previous job to a different S3 bucket. In cases where they copy fails, a link to the old JSON output object will be provided.

</blockquote></details>

That paragraph is already pretty long for an introduction.

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
