### PR TITLE
Update S3 documentation

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/977
- https://github.com/openmpf/openmpf/issues/1030
- https://github.com/openmpf/openmpf/issues/849
- https://github.com/openmpf/openmpf/issues/1496

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1497

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Object-Storage-Guide.md, line 25 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRblm-7fxGTRWE_KF2:-MzRblm-7fxGTRWE_KF3:bl83kmd) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L25)):*
> ```Markdown
>     - When using NGINX, exponential back off is used between retry attempts. There is a 500ms delay before the 
>       first retry. The delay doubles for each subsequent retry.
>     - When using S3, the AWS SDK's default retry strategy is used.
> ```

Move this line above the NGINX line since we're promoting S3 object storage before NGINX object storage in this guide now.
___
*[docs/docs/Object-Storage-Guide.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRfG7gA855gVM29Ao4:-MzRfG7gA855gVM29Ao5:b-w3wd4a) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L68)):*
> ```Markdown
>     - If you want to run a job where some media is in S3 and some is hosted elsewhere,
>       you can set `S3_UPLOAD_ONLY` to `true` as a media specific property on the media that is hosted elsewhere.
> - `S3_REGION` job property or `s3.region` system property
> ```

I was just reading about [CNAMEs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingCustomURLs). Basically, it seems they are a way to avoid specifying the region in the public S3 URL.

Our code appears to always provide the `S3_REGION` when building the S3 client. Could that prevent a CNAME from working correctly? For example, let's say the following CNAME is configured through the AWS console:

```
images.awsexamplebucket1.net CNAME    images.awsexamplebucket1.net.s3.ap-southeast-1.amazonaws.com.
```

If the user does not specify `S3_REGION` when creating the job, then we will default to `us-east-1`, which does not correspond with the actual region of `ap-southeast-1`. Will this cause a problem, or will the region setting simply be ignored by the S3 provider in this case? If a problem, we may need a way to not provide a region setting.

**Review by jrobble — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Object-Storage-Guide.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRfG7gA855gVM29Ao4:-MzRnQe36-TKRbjKAOtm:b-2ogw86) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I was just reading about [CNAMEs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingCustomURLs). Basically, it seems they are a way to avoid specifying the region in the public S3 URL.

Our code appears to always provide the `S3_REGION` when building the S3 client. Could that prevent a CNAME from working correctly? For example, let's say the following CNAME is configured through the AWS console:

```
images.awsexamplebucket1.net CNAME    images.awsexamplebucket1.net.s3.ap-southeast-1.amazonaws.com.
```

If the user does not specify `S3_REGION` when creating the job, then we will default to `us-east-1`, which does not correspond with the actual region of `ap-southeast-1`. Will this cause a problem, or will the region setting simply be ignored by the S3 provider in this case? If a problem, we may need a way to not provide a region setting.
</blockquote></details>

Our solution also requires the user to set `S3_HOST`. I just realized that CNAMEs hide the host. In the example above, all of `s3.ap-southeast-1.amazonaws.com` is hidden.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/Object-Storage-Guide.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRfG7gA855gVM29Ao4:-MzVYMpQ6-aMrtzYM1xQ:b-dpfjxf) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Our solution also requires the user to set `S3_HOST`. I just realized that CNAMEs hide the host. In the example above, all of `s3.ap-southeast-1.amazonaws.com` is hidden.
</blockquote></details>

As discussed, please mention that CNAMEs are not supported.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/Object-Storage-Guide.md, line 25 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRblm-7fxGTRWE_KF2:-MzVe6IVDWaxCimGwPTx:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L25)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Move this line above the NGINX line since we're promoting S3 object storage before NGINX object storage in this guide now.
</blockquote></details>

Done.
___
*[docs/docs/Object-Storage-Guide.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/145#-MzRfG7gA855gVM29Ao4:-MzVe770BG1rOoP6n1qA:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/af7c27e42df2f78f1754ea0fd581843c68ab10b5/docs/docs/Object-Storage-Guide.md#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, please mention that CNAMEs are not supported.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
