### PR TITLE
Update release notes for R6.0.1.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)

### CODE REVIEW

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @brosenberg42, @clnowacki, and @hhuangMITRE)

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)* status: all files reviewed, 3 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[docs/docs/CPP-Batch-Component-API.md, line 449 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCeXAIEUvHizfTqa2K:-MQCeXAIEUvHizfTqa2L:b-jcm76w) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/CPP-Batch-Component-API.md#L449)):*
The compose file linked here has the proper names for the properties with the MPF_PROP_ prefix, but the comment discussing how to use them still uses the old name and needs to be updated.

> ```
> https://github.com/openmpf/openmpf-docker/blob/32d072c9578441f2a07ec2da3bc3765aa1ff9cce/docker-compose.components.yml#L96
> ```
___
*[docs/docs/Release-Notes.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCfFfJ1t9v5QMLSXJ_:-MQCfFfJ1t9v5QMLSXJa:b-q01sqj) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/Release-Notes.md#L1)):*
> ```Markdown
> > **NOTICE:** This software (or technical data) was produced for the U.S. Government under contract, and is subject to the Rights in Data-General Clause 52.227-14, Alt. IV (DEC 2007). Copyright 2020 The MITRE Corporation. All Rights Reserved.
> ```

Will you be changing the copyright date here?
___
*[docs/docs/Release-Notes.md, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCgw0H3YWb3QGymcEB:-MQCgw0H3YWb3QGymcEC:b-315sco) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/Release-Notes.md#L61)):*
> ```Markdown
> ```
> 
> - Note that you can use the `OUTPUT_MERGE_WITH_PREVIOUS_TASK` setting on multiple tasks. For example, if you set it as a job property it will be applied to all tasks (with the exception of Markup - in which case the task before Markup is used), so you will only get the output of the last task in the pipeline. The last task will in inherit the detection type and algorithm of the first task in the pipeline.
> ```

Remove the extra "in" in the last sentence: "The last task will in inherit..."

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @hhuangMITRE)

___
*[docs/docs/CPP-Batch-Component-API.md, line 449 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCeXAIEUvHizfTqa2K:-MQD8bDzCs86Plq_DXCk:b-3tlws5) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/CPP-Batch-Component-API.md#L449)):*
> ACS_URL and ACS_SUBSCRIPTION_KEY can also be provided as job properties.

When provided as job properties, the `MPF_PROP_` prefix must be dropped. Maybe it would make the most sense to add an additional line to the comment in the compose file to make that clear, then we can leave the rest of the comment alone. What do you think? 

In general, I'd rather describe the property using the version without the prefix since under the hood the prefix is removed, and that way we can describe the behavior when the property is provided in a non-Docker way.

Note that @brosenberg42 and I agreed not to change openmpf-docker master with these comments since they are not critical, but rather add them to develop. As you can see [here](https://github.com/openmpf/openmpf-docker/blob/32d072c9578441f2a07ec2da3bc3765aa1ff9cce/docker-compose.components.yml#L96), I asked him to add comments to the other Azure services.
___
*[docs/docs/Release-Notes.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCfFfJ1t9v5QMLSXJ_:-MQDAyLN3ROQH20tAHRD:bgut84d) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/Release-Notes.md#L1)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Will you be changing the copyright date here?
</blockquote></details>

All of the copyright changes will go into develop in one fell swoop.
___
*[docs/docs/Release-Notes.md, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCgw0H3YWb3QGymcEB:-MQDCBIb8sDdTFxWVk54:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/Release-Notes.md#L61)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Remove the extra "in" in the last sentence: "The last task will in inherit..."
</blockquote></details>

Done.

**Review by clnowacki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @clnowacki, and @hhuangMITRE)

___
*[docs/docs/CPP-Batch-Component-API.md, line 449 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCeXAIEUvHizfTqa2K:-MQDEYwZBy8hEXd7dxoA:b4hluxc) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/CPP-Batch-Component-API.md#L449)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> ACS_URL and ACS_SUBSCRIPTION_KEY can also be provided as job properties.

When provided as job properties, the `MPF_PROP_` prefix must be dropped. Maybe it would make the most sense to add an additional line to the comment in the compose file to make that clear, then we can leave the rest of the comment alone. What do you think? 

In general, I'd rather describe the property using the version without the prefix since under the hood the prefix is removed, and that way we can describe the behavior when the property is provided in a non-Docker way.

Note that @brosenberg42 and I agreed not to change openmpf-docker master with these comments since they are not critical, but rather add them to develop. As you can see [here](https://github.com/openmpf/openmpf-docker/blob/32d072c9578441f2a07ec2da3bc3765aa1ff9cce/docker-compose.components.yml#L96), I asked him to add comments to the other Azure services.
</blockquote></details>

I think a line in the compose file that makes it clear what the distinction is between the two sets of names would be good. Something like: "These properties may be set as environment variables as well, by adding the MPF_PROP_ prefix to the property name, as seen below."

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @clnowacki, and @hhuangMITRE)

___
*[docs/docs/CPP-Batch-Component-API.md, line 449 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-MQCeXAIEUvHizfTqa2K:-MQDZJ3N1VGpk7PIl1OG:b5z4mng) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c0e4185209e9dad78c71e3dd50a768518f95b1ef/docs/docs/CPP-Batch-Component-API.md#L449)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

I think a line in the compose file that makes it clear what the distinction is between the two sets of names would be good. Something like: "These properties may be set as environment variables as well, by adding the MPF_PROP_ prefix to the property name, as seen below."
</blockquote></details>

Created a separate PR: https://github.com/openmpf/openmpf-docker/pull/134

**Review by clnowacki — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/123#-:-MQDaHQg-LElNlyC-h1f:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @brosenberg42, @clnowacki, and @hhuangMITRE)

**Pull request merged**
