### PR TITLE
Update release notes for R6.2.0.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1322

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128)

### CODE REVIEW

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/Release-Notes.md, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__bjSOB_71lkcZC3ig:-M__bjSP0s6Cb2-hnCz-:bno4c4i) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L30)):*
> ```Markdown
> <h3>Handle Variable Frame Rate Videos</h3>
> 
> - The WFM will attempt to detect if a video is constant frame rate (CFR) or variable frame rate (VFR) during media inspection. If no determination can be made, it will default to VFR behavior. If CFR, the JSON output object will have a `HAS_CONSTANT_FRAME_RATE=true` property in the `mediaMetadata` field.
> ```

Please spell out workflow manager instead of using 'WFM'
___
*[docs/docs/Release-Notes.md, line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__bxyc9S9FIhZblBgV:-M__bxyc9S9FIhZblBgW:b-hu6lbo) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L31)):*
> ```Markdown
> 
> - The WFM will attempt to detect if a video is constant frame rate (CFR) or variable frame rate (VFR) during media inspection. If no determination can be made, it will default to VFR behavior. If CFR, the JSON output object will have a `HAS_CONSTANT_FRAME_RATE=true` property in the `mediaMetadata` field.
> - When `MPFVideoCapture` handles a CFR video it will use OpenCV to set the frame position, unless the position is within 16 frames of the current position, in which it will iteratively use OpenCV `grab()` to advance to the desired frame. 
> ```

"in which case it will..."
___
*[docs/docs/Release-Notes.md, line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__cLCzEVMXnCxTwVHu:-M__cLD-6bW1LfKz0yGC:b4nt4jy) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L33)):*
> ```Markdown
> - When `MPFVideoCapture` handles a CFR video it will use OpenCV to set the frame position, unless the position is within 16 frames of the current position, in which it will iteratively use OpenCV `grab()` to advance to the desired frame. 
> - When `MPFVideoCapture` handles a VFR video it will always iteratively use OpenCV `grab()` to advance to the desired frame because setting the frame position directly has been shown to not work correctly on VFR videos.
> - When a video is split into multiple segments, `MPFVideoCapture` must iteratively use `grab()` to advance from frame 0 to the start of the segment. This introduces performance overhead. To mitigate this we recommend using fewer, and larger, video segments than those used for CFR videos.
> ```

I think "fewer segments" and "larger segments" are equivalent. I think recommending large segments would be sufficient, especially since the user controls the size of segments, but only controls the number of segments indirectly by specifying the size.
___
*[docs/docs/Release-Notes.md, line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__d8j17TttlFqy0OUc:-M__d8j17TttlFqy0OUd:b-toynwz) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L57)):*
> ```Markdown
> <h3>Updates</h3>
> 
> - [[#1299](https://github.com/openmpf/openmpf/issues/1299)] Improved artifact extraction performance when there is no rotation or flip
> ```

Add a period at the end of this sentence.

**Review by jrobble — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

**Review by clnowacki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[docs/docs/Release-Notes.md, line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__d8j17TttlFqy0OUc:-M_ap0bfASxoe74nuNN_:b1md8u5) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L57)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Just this one? There are many issue descriptions in the release notes that don't end in periods. Many aren't full sentences. I've defaulted to not using periods for issue descriptions unless I need to add another sentence to describe the issue.
</blockquote></details>

Ah, yes, I missed the fact that this is an issue title. Never mind.

**Review by brosenberg42 — APPROVED** [review]

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128)* status: all files reviewed, 4 unresolved discussions (waiting on @clnowacki)

___
*[docs/docs/Release-Notes.md, line 57 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-M__d8j17TttlFqy0OUc:-M_fr-nP3QdkhiXOgPA4:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/d2df9047191b5f4e4c282765538017c14628062c/docs/docs/Release-Notes.md#L57)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Ah, yes, I missed the fact that this is an issue title. Never mind.
</blockquote></details>

Done.

**Review by jrobble — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/128#-:-M_fr6B34xKf9KIdE9cw:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @clnowacki)

**Pull request merged**
