### PR TITLE
Update release notes for R7.0.0.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1552
- https://github.com/openmpf/openmpf/issues/1473

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1551
- https://github.com/openmpf/openmpf-components/pull/300
- https://github.com/openmpf/openmpf-contrib-components/pull/80
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/114
- https://github.com/openmpf/openmpf-java-component-sdk/pull/58
- https://github.com/openmpf/openmpf-python-component-sdk/pull/64

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)

### CODE REVIEW

**Review by brosenberg42 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @clnowacki)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 46 of 51 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)* status: 47 of 52 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`docs/docs/Release-Notes.md` line 68 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83fkTR66nwAN4EDXfk:-N83fkTR66nwAN4EDXfl:b-h4c7im) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L68)):*
> ```Markdown
>   definition. They do not need to be defined again.
> - This feature is a convenient alternative to creating persistent definitions using the `[POST] /rest/pipelines`,
>   `[POST] /rest/tasks`, and `[POST] /rest/actions` endpoints. For example, to quickly add or remove a motion
> ```

The sentence starting with "For example" is a fragment. Maybe change it to "For example, this feature could be used to quickly..."
___
*[`docs/docs/Release-Notes.md` line 76 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83g2AdEma5VmCyIfXB:-N83g2AeCG4TrxqztKL9:be385j5) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L76)):*
> ```Markdown
>   endpoint in order to manually specify segment boundaries. These values will override the normal segmenting behavior of
>   the Workflow Manager.
> - Not that overlapping ranges will be combined and large ranges may still be split up according to the value of
> ```

"Note that" instead of "Not that"
___
*[`docs/docs/Release-Notes.md` line 139 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83gnzlA0eGqPCs5f20:-N83gnzlA0eGqPCs5f21:b-2h0juq) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L139)):*
> ```Markdown
> 
> - Components that generate `MEDIA` tracks will result in new derivative `media` entries in the JSON output file. This
>   means it's possible to provide a single piece of media as in input and have more than one `media` entry in the JSON
> ```

Change "as in input" to "as an input"
___
*[`docs/docs/Release-Notes.md` line 180 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83hay2-uH4UW0X-GCQ:-N83hay2-uH4UW0X-GCR:b-psx869) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L180)):*
> ```Markdown
> - [[#1449](https://github.com/openmpf/openmpf/issues/1449)] Simon data is now refreshed when clicking the Processes tab
> - [[#1495](https://github.com/openmpf/openmpf/issues/1495)] Fix bug where invalid CSRF token found for `/workflow-manager/login`
> - [[#1501](https://github.com/openmpf/openmpf/issues/1501)] MPFVideoCapture now properly reads frames from videos with rotation metadata
> ```

Was 1501 fixed in 7.0 or 6.3.10 (see below)? Same for 1502 and 1503

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)* status: 47 of 52 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[`docs/docs/Release-Notes.md` line 68 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83fkTR66nwAN4EDXfk:-N84RedS92LDL1JSQtA9:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L68)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The sentence starting with "For example" is a fragment. Maybe change it to "For example, this feature could be used to quickly..."
</blockquote></details>

Done.



_Code quote:_
```Markdown
 For example, to quickly add 
```
___
*[`docs/docs/Release-Notes.md` line 76 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83g2AdEma5VmCyIfXB:-N84Rkn0-n69hKgnZIUe:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L76)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"Note that" instead of "Not that"
</blockquote></details>

Done.



_Code quote:_
```Markdown
Not that overlapping ranges
```
___
*[`docs/docs/Release-Notes.md` line 139 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83gnzlA0eGqPCs5f20:-N84Rw4k30A6wKTm2B0W:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L139)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Change "as in input" to "as an input"
</blockquote></details>

Done.



_Code quote:_
```Markdown
media as in input and have more than
```
___
*[`docs/docs/Release-Notes.md` line 180 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/153#-N83hay2-uH4UW0X-GCQ:-N84RxPD1enI56pk8qgY:birx4uy) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3c1cb268e92827ae5a73bba89c84c30335f2eac2/docs/docs/Release-Notes.md#L180)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Was 1501 fixed in 7.0 or 6.3.10 (see below)? Same for 1502 and 1503
</blockquote></details>

Good catch. Removed from 7.0.0.

**Review by clnowacki — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/153)* status: 46 of 52 files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
