### PR TITLE
Update list of possible job statuses

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1349

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1364

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf-kJbPBettuQp1o9U4:-Mf-kJbPBettuQp1o9U5:b33l539) (no related file):*
Since you're making changes to this doc, I kindly request that you also address https://github.com/openmpf/openmpf/issues/1361.

---
___
*[docs/docs/html/REST-API.html, line 892 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf-jqqH5os21rwzO_c7:-Mf-jqqI5WlYR1kZ3oaj:b-iiwexe) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/20e3b6453c99ff5d6ca55d3f8804c0d2a61a2286/docs/docs/html/REST-API.html#L892)):*
> ```HTML
>                         INITIALIZED (the job has been initialized but not started),
>                         IN_PROGRESS, IN_PROGRESS_ERRORS, IN_PROGRESS_WARNINGS
>                         COMPLETE, COMPLETE_WITH_ERRORS, COMPLETE_WITH_WARNINGS,
> ```

Please add `CANCELLED_BY_SHUTDOWN`.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/html/REST-API.html, line 910 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf4Teg19VxxKc-ihe_9:-Mf4Teg2DX--sN7uIozU:b8faj6l) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a3b05e5155507f26a133eeefcbdd5f4f3f47524d/docs/docs/html/REST-API.html#L910)):*
> ```HTML
>                     <td style="width:40%;">terminal</td>
>                     <td style="width:20%;">boolean</td>
>                     <td style="width:40%;">True if jobStatus is JOB_CREATION_ERROR, COMPLETE, CANCELLED, or ERROR; otherwise false</td>
> ```

Please update the description of the `terminal` field here to mention the correct job status fields.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf-kJbPBettuQp1o9U4:-MfZ3D_55TblcL72X5SE:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since you're making changes to this doc, I kindly request that you also address https://github.com/openmpf/openmpf/issues/1361.
</blockquote></details>

Done.

---
___
*[docs/docs/html/REST-API.html, line 892 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf-jqqH5os21rwzO_c7:-MfZ3E2h82av-HzeZbL5:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/20e3b6453c99ff5d6ca55d3f8804c0d2a61a2286/docs/docs/html/REST-API.html#L892)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add `CANCELLED_BY_SHUTDOWN`.
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 910 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-Mf4Teg19VxxKc-ihe_9:-MfZ3F2J6jvbvQOCtXGA:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/a3b05e5155507f26a133eeefcbdd5f4f3f47524d/docs/docs/html/REST-API.html#L910)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the description of the `terminal` field here to mention the correct job status fields.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/html/REST-API.html, line 148 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-MfZ4aMeAhQimy1Etrg4:-MfZ4aMeAhQimy1Etrg5:b-m14ux8) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/9e1df3d8b55c48a2b913246111f2a1dab77ed437/docs/docs/html/REST-API.html#L148)):*
> ```HTML
>     <div style='page-break-after:always'>
>         <h1>OpenMPF Workflow Manager REST API</h1>
>         <h2>Version 5.1.0 (build 20200804)</h2>
> ```

Please change the date and increment the version number. (I think sub-minor is fine.)
___
*[docs/docs/html/REST-API.html, line 161 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/132#-MfZ4fIvD97qfWLQKKXn:-MfZ4fIvD97qfWLQKKXo:b-ldr1r0) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/9e1df3d8b55c48a2b913246111f2a1dab77ed437/docs/docs/html/REST-API.html#L161)):*
> ```HTML
>         <br/>
>     </div>
>     <div class='footer'>Last updated on: Tue Aug 4, 2020</div>
> ```

Please update this date.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
