### PR TITLE
Update release notes for R8.0.0.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1737

**Related PRs:**

- https://github.com/openmpf/openmpf.github.io/pull/173
- https://github.com/openmpf/openmpf/pull/1738
- https://github.com/openmpf/openmpf-components/pull/345
- https://github.com/openmpf/openmpf-contrib-components/pull/89
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/122
- https://github.com/openmpf/openmpf-java-component-sdk/pull/64
- https://github.com/openmpf/openmpf-python-component-sdk/pull/76

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/docs/Release-Notes.md` line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NkMlGD164T6ZhUtWziy:-NkMlGD2-qcc7DgUZgf9:b70q1f0) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/56adbbfd522497b5619432da5c68e6ff315bab4d/docs/docs/Release-Notes.md#L30)):*
> ```Markdown
> <h3>Updates</h3>
> 
> - [[#1693](https://github.com/openmpf/openmpf/issues/1693)] Add property to enable/disable SAS in AzureSpeech
> ```

THis is bad

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`docs/docs/Release-Notes.md` line 9 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBl-t5EejG3ATTDitj:-NmBl-t5EejG3ATTDitk:b-h3kycc) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L9)):*
> ```Markdown
> 
> <h3>Documentation</h3>
> ```

Unless this breaks protocol, I think the Documentation section should come after the sections describing new features/functionality. Otherwise, it is out of context and a user doesn't know what these terse descriptions are referring to.
___
*[`docs/docs/Release-Notes.md` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBkgJO68YoTIJ27UrI:-NmBkgJO68YoTIJ27UrJ:baik3kd) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L12)):*
> ```Markdown
> - Created a new [OpenID Connect Guide](OpenID-Connect-Guide/index.html).
> - Updated the [Admin Guide](Admin-Guide/index.html) and [User Guide](User-Guide/index.html) to remove
>   `/workflow-manager` from the Workflow Manager base URL. The Admin Guide includes a section for new the Hawtio web
> ```

The Admin Guide includes a section for *the* new Hawtio web console.
___
*[`docs/docs/Release-Notes.md` line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBlnyq6Ahi1JZRKfpE:-NmBlnyq6Ahi1JZRKfpF:b-gfectk) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L49)):*
> ```Markdown
> 
> <h3>Component API Updates</h3>
> ```

This section could use a sentence to explain why these were removed.
___
*[`docs/docs/Release-Notes.md` line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBlxPUD7hBKTTizJa_:-NmBlxPUD7hBKTTizJaa:b-gwxa6e) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L57)):*
> ```Markdown
> 
> - Each component's `descriptor.json` now requires an `algorithm.trackType` field. This is used by the Workflow Manager
>   to determine the kind of tracks that may be generated by the component (e.g. `FACE`, `TEXT`, `CLASS`, etc.). This now
> ```

This *is* now used...
___
*[`docs/docs/Release-Notes.md` line 116 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBmXt6-CjX3D6pKf9U:-NmBmXt6-CjX3D6pKf9V:bqdjrrd) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L116)):*
> ```Markdown
>   tracks you can provide a list of valid values. For example, `CLASSIFICATION=car;truck;bus`.
> - The [Trigger Guide](Trigger-Guide/index.html) goes into more detail and provides an example of a pipeline with
>   multiple speech-to-text stages. `TRIGGER` is the used to select which speech-to-text algorithm is executed based on
> ```

Remove 'the' between 'is' and 'used' -- 'TRIGGER' is used...
___
*[`docs/docs/Release-Notes.md` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBn17xCCGhvn3d2-LL:-NmBn17xCCGhvn3d2-LM:b-rtcu05) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L140)):*
> ```Markdown
> 
> - This new component utilizes [CLIP](https://github.com/openai/CLIP) to classify images using the 80 COCO classes, 1000
>   ImageNet classes, or a list of user-provided classes. It can run on a CPU or GPU and make calls to an NVIDIA Triton
> ```

It can run on a CPU or GPU, and *can* make calls to ...

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[`docs/docs/Release-Notes.md` line 9 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBl-t5EejG3ATTDitj:-NmCCx-0BRvmbr-oUgll:br1rnuh) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L9)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Unless this breaks protocol, I think the Documentation section should come after the sections describing new features/functionality. Otherwise, it is out of context and a user doesn't know what these terse descriptions are referring to.
</blockquote></details>

So far I've always made sure to list the docs first. It's been that way in prev. release notes. The reason is that it usually provides an outline of the biggest features and changes to the core. Yeah, a reader would have to keep reading the individual sections that follow to learn more.

I try to list the doc changes in order of importance, and also just the individual sections in the same order.
___
*[`docs/docs/Release-Notes.md` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBkgJO68YoTIJ27UrI:-NmCE55w9R91Nh5HPF7o:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L12)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The Admin Guide includes a section for *the* new Hawtio web console.
</blockquote></details>

Done.
___
*[`docs/docs/Release-Notes.md` line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBlnyq6Ahi1JZRKfpE:-NmCFDYNEchnWNP9aSPM:b-rsv3s7) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L49)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

This section could use a sentence to explain why these were removed.
</blockquote></details>

I moved the "Packaging and Deployment" section above this one since that change was the main motivator. I also added a sentence to provide context.
___
*[`docs/docs/Release-Notes.md` line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBlxPUD7hBKTTizJa_:-NmCFbtr-zBShu5ovXOI:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L57)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

This *is* now used...
</blockquote></details>

Done.
___
*[`docs/docs/Release-Notes.md` line 116 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBmXt6-CjX3D6pKf9U:-NmCFmJgELRkuyyJa8Wf:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L116)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Remove 'the' between 'is' and 'used' -- 'TRIGGER' is used...
</blockquote></details>

Done.
___
*[`docs/docs/Release-Notes.md` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/173#-NmBn17xCCGhvn3d2-LL:-NmCGBui7x5hOfblTN0m:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0028afb025edf4ee431e9c1277a3468ea0a49bf8/docs/docs/Release-Notes.md#L140)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

It can run on a CPU or GPU, and *can* make calls to ...
</blockquote></details>

Done.

**Review by clnowacki — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Review by clnowacki — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
