### PR TITLE
Added Feed Forward Guide.

### PR DESCRIPTION
**Pull request by jrobble**
Fixed deployment package .json name in Build Guide.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/28)

### CODE REVIEW

**Comment by clnowacki** [comment]
Reviewed 19 of 21 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/docs/Feed-Forward-Guide.md, line 6 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqPu2yURjREMu0zfco:-KwqPu2yURjREMu0zfcp:b-tvbufv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L6)):*
> ```Markdown
> 
> Feed forward is an optional behavior of OpenMPF that allows tracks from one detection stage of the pipeline to be directly “fed into” the next stage. It differs from the default segmenting behavior in the following major ways:
> ```

In the first sentence of 1.: I would word it as "The next stage will only look at the frames that had detections in the previous stage.

---

*[docs/docs/Feed-Forward-Guide.md, line 7 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqPs1dlA7toeUDitha:-KwqPImdDsRF98Gc691W:b-irk0by) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L7)):*
> ```Markdown
> Feed forward is an optional behavior of OpenMPF that allows tracks from one detection stage of the pipeline to be directly “fed into” the next stage. It differs from the default segmenting behavior in the following major ways:
> 
> 1. The next stage will only look at the frames from the previous stage which had detections. The default segmenting behavior results in “filling the gaps” so that the next stage looks at all the frames from the between the start and end frames of the feed forward track, regardless if a detection was actually found in those frames.
> ```

change "all the frames from the between the start..." Either "from the" or "between the"

Also change "regardless if" to "regardless of whether"

---

*[docs/docs/Feed-Forward-Guide.md, line 11 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqQX195WIkZHaZB7iT:-KwqQX195WIkZHaZB7iU:b-tlzprc) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L11)):*
> ```Markdown
> 2. The next stage can be configured to only look at the detection regions for the frames in the feed forward track. The default segmenting behavior does not pass the detection region information to the next stage, so the next stage looks at the whole frame region for every frame in the segment.
> 
> 3. The next stage will process one sub-job per track generated in the previous stage. If the previous stage generated more than one track in a frame, say 3 tracks, then the next stage will process that frame a total of 3 times. Feed forward can be configured such that only the detection regions for those tracks are processed. If they are non-overlapping then there is no duplication of work. The default segmenting behavior will result one sub-job that captures the frame associated with all 3 tracks.
> ```

The default segmenting behavior will result *in* one sub-job...

---

*[docs/docs/Feed-Forward-Guide.md, line 20 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqR1MtfGXLOBAk2qjt:-KwqR1MuFF-IJxA_LuhV:bsnkb9c) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L20)):*
> ```Markdown
> 1. You have an algorithm that isn’t capable of breaking down a frame into regions of interest. For example, face detection can take a whole frame and generate a separate detection region for each face in the frame. On the other hand, Caffe classification will take that whole frame and generate a single detection that’s the size of the frame’s width and height. Caffe will produce better results if it operates on smaller regions that only capture the desired object to be classified. Using feed forward, you can create a pipeline so that Caffe only processes regions with motion in them.
> 
> 2. You wish to reduce processing time by creating a pipeline in which algorithms are chained from fastest to slowest. For example, a pipeline that starts motion detection will only feed regions with motion to the next stage, which may be a compute-intensive face detection algorithm. Reducing the amount of data that algorithm needs to process will speed up run times.
> ```

For example, a pipeline that starts *with* motion detection...

---

*[docs/docs/Feed-Forward-Guide.md, line 70 at r2](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-Kwtr9JRNVWWiOt4xbi2:-Kwtr9JRNVWWiOt4xbi3:bg7r778) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2f4fdb10cab4b719640d8fcad581bf242f93fc56/docs/docs/Feed-Forward-Guide.md#L70)):*
> ```Markdown
> # MPFVideoCapture and MPFImageReader Tools
> 
> The [OpenMPF C++ SDK](CPP-Component-API/) includes utilities that make it easier to support feed forward in your components. The `MPFVideoCapture` class is wrapper around OpenCV's `cv::VideoCapture` class. `MPFVideoCapture` works very similarly to `cv::VideoCapture`, except that it might modify the video frames based on job properties. From the point of view of someone using `MPFVideoCapture`, these modifications are mostly transparent. `MPFVideoCapture` makes it look like you are reading the original video file.
> ```

The `MPFVideoCapture` class is *a* wrapper...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28)*

**Comment by jrobble** [comment]
Review status: 18 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/docs/Feed-Forward-Guide.md, line 6 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqPu2yURjREMu0zfco:-KwuF9Puy29csKYrGTpB:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L6)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

In the first sentence of 1.: I would word it as "The next stage will only look at the frames that had detections in the previous stage.
</blockquote></details>

Done.

---

*[docs/docs/Feed-Forward-Guide.md, line 7 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqPs1dlA7toeUDitha:-KwuF9mvVbayUGzG4D03:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L7)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

change "all the frames from the between the start..." Either "from the" or "between the"

Also change "regardless if" to "regardless of whether"
</blockquote></details>

Done.

---

*[docs/docs/Feed-Forward-Guide.md, line 11 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqQX195WIkZHaZB7iT:-KwuFAfdAAfBb7wLxjk7:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L11)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The default segmenting behavior will result *in* one sub-job...
</blockquote></details>

Done.

---

*[docs/docs/Feed-Forward-Guide.md, line 20 at r1](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwqR1MtfGXLOBAk2qjt:-KwuFB0WeL5TSsg1Tz0Z:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/53d62f53194a2d684fedd801acbf802da674d210/docs/docs/Feed-Forward-Guide.md#L20)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

For example, a pipeline that starts *with* motion detection...
</blockquote></details>

Done.

---

*[docs/docs/Feed-Forward-Guide.md, line 70 at r2](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-Kwtr9JRNVWWiOt4xbi2:-KwuFBn0-xKM77mjnY4h:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/2f4fdb10cab4b719640d8fcad581bf242f93fc56/docs/docs/Feed-Forward-Guide.md#L70)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The `MPFVideoCapture` class is *a* wrapper...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28)*

**Comment by clnowacki** [comment]
Reviewed 4 of 4 files at r3.
Review status: 18 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[docs/docs/Feed-Forward-Guide.md, line 132 at r3](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwuQ-NHXKkc5qugE39Q:-KwuQ-NHXKkc5qugE39R:b-k4pc0i) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f87433bead0415b64b04143e0b2df6e036029dcb/docs/docs/Feed-Forward-Guide.md#L132)):*
> ```Markdown
> 
> ```
> CAFFE GOOGLENET DETECTION (WITH FEED FORWARD REGION) TASK
> ```

For some strange reason, the word "WITH" renders in purple on the version of firefox I have on my VM. It doesn't happen on the first occurrence, but all subsequent ones. Same thing for the OCV FACE actions and tasks below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28)*

**Comment by jrobble** [comment]
*[docs/docs/Feed-Forward-Guide.md, line 132 at r3](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-KwuQ-NHXKkc5qugE39Q:-KwuSFIMsNzXg8xP_Qq9:b-yoxtd0) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f87433bead0415b64b04143e0b2df6e036029dcb/docs/docs/Feed-Forward-Guide.md#L132)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

For some strange reason, the word "WITH" renders in purple on the version of firefox I have on my VM. It doesn't happen on the first occurrence, but all subsequent ones. Same thing for the OCV FACE actions and tasks below.
</blockquote></details>

Yeah, me too. It seems to have something to do with Read the Docs code highlighting. There is some odd highlighting on the Installation Guide page too. I don't think it's a big deal so let's go ahead and land this. If we have time we can address it later. I couldn't find an easy way to disable it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28)*

**Comment by clnowacki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf.github.io/28#-:-Kwus5juT6S5VzK67bAL:bnfp4nl)*

**Pull request merged**
