### PR TITLE
Add Node Guide

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Review status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @jrobble and @brosenberg42)

---

*[docs/docs/Node-Guide.md, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo2t5s8BN7JALYdeAA:-LEo2t5s8BN7JALYdeAB:b-wfzxza) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L35)):*
> ```Markdown
> # Setting up a Spare Node
>  
> A spare node is defined as a node that is not configured during the OpenMPF installation process, which means that the only way to create a spare node is to configure it manually, or clone it from an existing child node. We recommend the latter, which is easy to do if your nodes are VMs. Make sure not to clone the master node because only one node in the OpenMPF cluster should be running the WFM. Instead, clone a child node. If the cluster only consists of the master node, then please follow the *Configure the OpenMPF Cluster* step in the [Installation Guide](Installation-Guide/index.html#openmpf-installation) again to add a new child node.
> ```

Is it actually possible to configure the spare node manually? If so, the process should be documented.

---

*[docs/docs/Node-Guide.md, line 47 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo0MKq2EVv72drQHHp:-LEo0MKr8LnlBgBD1xIP:bmyi4g5) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L47)):*
> ```Markdown
> 3. Use the dialog to give the machine a new name. Be sure to check the "Reinitialize the MAC address of all network cards" box. Then click "Continue".
> 
> 4. Select "Full clone" or "Linked clone", depending on your preference. Eventually, click the "Clone" button.
> ```

I don't think a linked clone will work. I am pretty sure that to run a linked clone, VirtualBox needs access to the original VM. 

---

*[docs/docs/Node-Guide.md, line 79 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo1dIw1U1bIN3yuw7E:-LEo1dIw1U1bIN3yuw7F:b-tnvf34) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L79)):*
> ```Markdown
> 9. In the editor, look for the line that begins with `IPADDR0=`. Change the IP address after the `=` to a different IP address on the same subnet as the other nodes in the OpenMPF cluster. Save your changes and exit the editor.
> 
>     >**NOTE**: This step is used to set a static IP address. If not already the case, change `BOOTPROTO=dhcp` to `BOOTPROTO=none` in this file.
> ```

Why can't it use DHCP?

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57)*

**Comment by jrobble** [comment]
Mention that DHCP works.

---

Review status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @jrobble and @brosenberg42)

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-:-LEo_2KO1tbb2h7PZEJm:b9ywsyl)*

**Comment by jrobble** [comment]
*[docs/docs/Node-Guide.md, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo2t5s8BN7JALYdeAA:-LEo_mHt1n9LaePuCTt9:b151h7j) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L35)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Is it actually possible to configure the spare node manually? If so, the process should be documented.
</blockquote></details>

Remove "configure it manually"

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57)*

**Comment by jrobble** [comment]
Review status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

---

*[docs/docs/Node-Guide.md, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo2t5s8BN7JALYdeAA:-LEqzmhq8icVHMHqlWNB:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove "configure it manually"
</blockquote></details>

Done.

---

*[docs/docs/Node-Guide.md, line 47 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo0MKq2EVv72drQHHp:-LEqvyAc1ffuIB2bB8zn:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L47)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think a linked clone will work. I am pretty sure that to run a linked clone, VirtualBox needs access to the original VM. 
</blockquote></details>

Done.

---

*[docs/docs/Node-Guide.md, line 79 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-LEo1dIw1U1bIN3yuw7E:-LEqxoFcD9Z4B41XciQZ:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/f778a1c6b136917ce46e93c52d4ba3d4a3ff3deb/docs/docs/Node-Guide.md#L79)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Why can't it use DHCP?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Review status: 0 of 31 files reviewed, all discussions resolved (waiting on @brosenberg42)

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/57#-:-LEtxOjqAGDgn8RO7P8Q:bnfp4nl)*

**Pull request merged**
