### PR TITLE
Updating documentation for new media metadata field in REST API.

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/119)

### CODE REVIEW

**Comment by hhuangMITRE** [comment]
I'm planning to automatically push this documentation update for REST API once the corresponding skip-media-inspection branch lands, and remove this branch from repo afterwards.

**Comment by jrobble** [comment]
___
*[docs/docs/html/REST-API.html, line 1903 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/119#-MDwRHzn3RsdqsG7V2db:-MDwRHzo8JOWF9dYSS1a:b-qj82yo) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/86e86321c4f0396533f2601ad6032be87fb0bffe/docs/docs/html/REST-API.html#L1903)):*
> ```HTML
>                         Note that the batch jobs and streaming jobs share a range of valid job ids. OpenMPF guarantees
>                         that the ids of a streaming job and a batch job will be unique. Also, note that all provided
>                         URIs must be properly encoded.
> ```

Please add a new "paragraph" here (surrounded by break lines like the others in this Description) where you briefly describe media metadata. You don't have to list all of the required properties like you did in the other section. One or two sentences would work.

I asked you to add the same sentences to `JobController.java` in your other PR.

**Comment by jrobble** [comment]
___
*[docs/docs/html/REST-API.html, line 148 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/119#-MDwN94L8HVOWLSh2f-Z:-MDwN94L8HVOWLSh2f-_:b-wk2dqe) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/86e86321c4f0396533f2601ad6032be87fb0bffe/docs/docs/html/REST-API.html#L148)):*
> ```HTML
>     <div style='page-break-after:always'>
>         <h1>OpenMPF Workflow Manager REST API</h1>
>         <h2>Version 5.0.0 (build 20200616)</h2>
> ```

Please update this to `Version 5.1.0 (build 20200804)`.

**Comment by jrobble** [comment]
> Ah sorry, I remembered that we can just update the documentation directly so I've closed the PR for this branch.

In general, we try to land changes to this repo via PR, so I reopened this. We used to make changes to working files (generated from Swagger) for the REST API HTML in an internal repo, but we've decided to abandon that in favor of just manually updating the files in this repo directly. You didn't need a PR to update the internal repo.

Also, maybe there was a time when we were in a rush and didn't go through the full PR process to land to this repo. I don't remember. Sorry for any confusion.

**Comment by jrobble** [comment]
Still discussing if we want to land this to master or develop. Will let you know soon.

**Comment by jrobble** [comment]
Please go ahead and land this to develop.

**Pull request merged**
