### PR TITLE
Document transient pipelines

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1428

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1472

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)

### CODE REVIEW

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/html/REST-API.html, line 604 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8ZiKjBaWKrmZVaATF:-N-8ZiKjBaWKrmZVaATG:bjj423f) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L604)):*
> ```HTML
>                     A list of temporary tasks that may be used by this pipeline. The order that
>                     the tasks appear in this list does not affect the order that the tasks
>                     are executed, that is defined in the <code>pipeline</code> field.
> ```

Instead of a comma between 'executed' and 'that', let's use an em-dash.
___
*[docs/docs/html/REST-API.html, line 686 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8_Oi8BKZko6zpEimE:-N-8_Oi8BKZko6zpEimF:b-i16oha) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L686)):*
> ```HTML
>                 <td style='width:30%;'>
>                     The name of the algorithm that this action will execute. It must be a
>                     preexisting algorithm already added to Workflow Manager
> ```

Add a period at the end of the second sentence.
___
*[docs/site/html/REST-API.html, line 1929 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8kd2S0elSP6Sgpa_j:-N-8kd2T1c6wQiP_YBr2:bidskm1) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/site/html/REST-API.html#L1929)):*
> ```HTML
>                     <td class='td-alignment-small'><b>Description</b></td>
>                     <td class='td-alignment-std'>
>                         The pipelineName should be one of the values in 'rest/pipelines', and the component associated
> ```

We should mention here that a pipelineDefinition could be provided in the job request, instead of a pipelineName.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[docs/docs/html/REST-API.html, line 444 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8vg7221b2qzj0Mmo7:-N-8veO68UoHHwszyPb7:biop1hf) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L444)):*
> ```HTML
>                     <td style='width:30%;'>
>                         The name of the pipeline used to process the media. Obtained from
>                         'rest/pipelines'. One of pipelineName or pipelineDefinition must be
> ```

Should we use `<code>` for "pipelineName" and "pipelineDefinition" here and in the pipelineDefinition section below ?
___
*[docs/docs/html/REST-API.html, line 602 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8wjvoEbGPmHM-AyaT:-N-8wWKP4Q5WVYDij75U:bpiq56d) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L602)):*
> ```HTML
>                 <td style='width:10%;'>array&lt;TransientTask></td>
>                 <td style='width:30%;'>
>                     A list of temporary tasks that may be used by this pipeline. The order that
> ```

Do we want to replace "temporary" with "transient"? It appears a few different places in this file.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[docs/docs/html/REST-API.html, line 444 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8vg7221b2qzj0Mmo7:-N-P4XKX9wDBe2-7bHOD:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L444)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we use `<code>` for "pipelineName" and "pipelineDefinition" here and in the pipelineDefinition section below ?
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 602 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8wjvoEbGPmHM-AyaT:-N-900Ei-FxQ4-auoGUo:b-rtz0ex) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L602)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we want to replace "temporary" with "transient"? It appears a few different places in this file. 
</blockquote></details>

I think that it is better to use a simpler more colloquial term in a description. Reusing word in its own definition is bad. When documentation is just the field name with a few generic words added around it, it feels bad or like it was auto generated.
___
*[docs/docs/html/REST-API.html, line 604 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8ZiKjBaWKrmZVaATF:-N-P3r0a5sxwqmZxhl_2:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L604)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Instead of a comma between 'executed' and 'that', let's use an em-dash.
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 686 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8_Oi8BKZko6zpEimE:-N-P3wrQ4QCcDG_Xchzj:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L686)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Add a period at the end of the second sentence.
</blockquote></details>

Done.
___
*[docs/site/html/REST-API.html, line 1929 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8kd2S0elSP6Sgpa_j:-N-P7GyD31s2HyNKMsIx:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/site/html/REST-API.html#L1929)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

We should mention here that a pipelineDefinition could be provided in the job request, instead of a pipelineName.
</blockquote></details>

Done.

**Review by clnowacki — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)* status: all files reviewed, 2 unresolved discussions (waiting on @jrobble)

**Review by jrobble — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

___
*[docs/docs/html/REST-API.html, line 602 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/149#-N-8wjvoEbGPmHM-AyaT:-N-QAjZi91XQcFnp7DOl:b-d1trer) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/3afbafbcbb689efd2dbb9e3b92388dccad69ea90/docs/docs/html/REST-API.html#L602)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think that it is better to use a simpler more colloquial term in a description. Reusing word in its own definition is bad. When documentation is just the field name with a few generic words added around it, it feels bad or like it was auto generated.
</blockquote></details>

Ok. I'm fine with how it is. In general, I just want to make sure this is a conscious choice and not just a carry over from before we decided to use the word "transient".

**Pull request merged**
