### PR TITLE
Feature/callback status

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1396

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy6ms1971Wnpsb17N0:-Mvy6ms1971Wnpsb17N1:bo8c4rw) (no related file):*
Please update the "Updating Online Documentation" section of the Contributor Guide to explain the new steps for generating, serving, and committing changes to the documentation. 

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvyGKMM4MLFGp6psXBa:-MvyGKMM4MLFGp6psXBb:ba0g57i) (no related file):*
I'm not saying that we need to make this part of this PR, but in lieu of regenerating all of the screenshots, what do you think about scrubbing the version label in the top banner from the UI in each of the existing screenshots since now we have a mix of old and new pics? It may be less confusing that way. Also, the old screenshots have the "Status" drop-down on the right side, which should also be scrubbed.

We can leave the version on the login page, or update the HTML using dev tools to some placeholder value to make it clear in the screenshot that it will change.

---
___
*[docs/docs/html/REST-API.html, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy8a2B1m8Uf8xr0Yxl:-Mvy8a2B1m8Uf8xr0Yxm:b9cgpnb) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L173)):*
> ```HTML
>     <div style='page-break-after:always'>
>         <h1>OpenMPF Workflow Manager REST API</h1>
>         <h2>Version 6.2.5</h2>
> ```

Update the version.
___
*[docs/docs/html/REST-API.html, line 186 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy8bn5DGYihklnmk4_:-Mvy8bn5DGYihklnmk4a:bf4ygds) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L186)):*
> ```HTML
>         <br/>
>     </div>
>     <div class='footer'>Last updated on: September 7, 2021</div>
> ```

Update this date.
___
*[docs/docs/html/REST-API.html, line 811 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvtqWPC80DH4ry-J-b2:-MvtqWPC80DH4ry-J-b3:b-gwnlwr) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L811)):*
> ```HTML
>                         Status of the HTTP POST to TiesDb. Possible statuses are "JOB RUNNING",
>                         "IN PROGRESS", "NOT REQUESTED", "COMPLETE", and
>                         "ERROR: &lt;description&gt;".
> ```

Mention that if there's an `ERROR` then the value will be `ERROR: <message>`

Also, please remove the `: &lt;description&gt;` part.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy6ms1971Wnpsb17N0:-Mw1c6NXBFfHK6eyVjz_:b-csdzpr) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the "Updating Online Documentation" section of the Contributor Guide to explain the new steps for generating, serving, and committing changes to the documentation. 
</blockquote></details>

This change is not related to the callback status changes. It should go on https://github.com/openmpf/openmpf.github.io/pull/141 which needs to land first.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvyGKMM4MLFGp6psXBa:-Mw1lu6T2muD4EmVC2I2:bxt88pw) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm not saying that we need to make this part of this PR, but in lieu of regenerating all of the screenshots, what do you think about scrubbing the version label in the top banner from the UI in each of the existing screenshots since now we have a mix of old and new pics? It may be less confusing that way. Also, the old screenshots have the "Status" drop-down on the right side, which should also be scrubbed.

We can leave the version on the login page, or update the HTML using dev tools to some placeholder value to make it clear in the screenshot that it will change.
</blockquote></details>

I disagree with the premise that someone would be confused by a version number changing. I don't think any of the tasks listed above provide value to our users.

---

**Comment by jrobble** [comment]
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy6ms1971Wnpsb17N0:-Mw2EnxD8fAQvJrEUbiI:b-qhvtwi) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This change is not related to the callback status changes. It should go on https://github.com/openmpf/openmpf.github.io/pull/141 which needs to land first.
</blockquote></details>

Sure. I left a comment on that PR.

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy6ms1971Wnpsb17N0:-Mw7keCWA4CAtsvOFU6p:b-69252g) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Sure. I left a comment on that PR.
</blockquote></details>

I don't mind either way, but I thought you were going to put the change in PR #141. Your updates look good. One minor comment below.

---
___
*[docs/docs/Contributor-Guide.md, line 224 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mw7pBQ3-JxQymZfxLuz:-Mw7pBQ47rpudrovcQLX:b-xdki9z) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/b98ba54d7293c59800e8aeb9f5cb1b873b05d367/docs/docs/Contributor-Guide.md#L224)):*
Although `openmpf.github.io/_site` is ignored, we should be clear here and say:

> Commit all of the generated files and generate a pull request to merge them into the develop branch. Note that `_site` is in `.gitignore` and should not be committed.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: 56 of 63 files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy6ms1971Wnpsb17N0:-Mw7sF_644PF7IL2hB1C:bpj0dx1) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't mind either way, but I thought you were going to put the change in PR #141. Your updates look good. One minor comment below.
</blockquote></details>

I reverted on this and made the change on #141 

---
___
*[docs/docs/Contributor-Guide.md, line 224 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mw7pBQ3-JxQymZfxLuz:-Mw7sCuq9WZQw2S49Mo2:bkjwxq2) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/b98ba54d7293c59800e8aeb9f5cb1b873b05d367/docs/docs/Contributor-Guide.md#L224)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Although `openmpf.github.io/_site` is ignored, we should be clear here and say:

> Commit all of the generated files and generate a pull request to merge them into the develop branch. Note that `_site` is in `.gitignore` and should not be committed.

</blockquote></details>

Done on other pr

**Review by jrobble — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvyGKMM4MLFGp6psXBa:-Mw82Kau25w-UmnHS3Sj:bvp5zfg) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I disagree with the premise that someone would be confused by a version number changing. I don't think any of the tasks listed above provide value to our users.
</blockquote></details>

Let's talk about this later. We'll create a separate issue and PR if need be.

---

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: 13 of 63 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/html/REST-API.html, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy8a2B1m8Uf8xr0Yxl:-MwRODen06BihfywKNEm:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L173)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update the version.
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 186 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-Mvy8bn5DGYihklnmk4_:-MwROVvQ7zJmhOz1Wrwp:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L186)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update this date.
</blockquote></details>

Done.
___
*[docs/docs/html/REST-API.html, line 811 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvtqWPC80DH4ry-J-b2:-MwROw6I3gbJAShXAX0w:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L811)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Mention that if there's an `ERROR` then the value will be `ERROR: <message>`

Also, please remove the `: &lt;description&gt;` part.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 48 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: 17 of 63 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/html/REST-API.html, line 811 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/142#-MvtqWPC80DH4ry-J-b2:-MwRezUuEaa0G2E8x2MJ:b-z7xucs) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/0ea001c8b8f2c4e6cd1a91d20e7abc92f35659ba/docs/docs/html/REST-API.html#L811)):*
Please address this:

> please remove the : &lt;description&gt; part.

**Review by jrobble — APPROVED** [review]
> Reviewed 46 of 48 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
