### PR TITLE
added steps for hotfix pull request

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1377

NOTE: For an unknown reason, I was not able to build the docs using the build-site.sh script. Please generate and update this PR. Thank you!

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: all files reviewed, 2 unresolved discussions (waiting on @clnowacki)

___
*[docs/docs/Contributor-Guide.md, line 138 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg6YuER0zFJ3492G0YQ:-Mg6YuES1d5HuOs8MM5g:b5aypuu) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/4324c00c4e81e6e43d4f2d04fa54d9937b85231b/docs/docs/Contributor-Guide.md#L138)):*
> ```Markdown
> When an OpenMPF project administrator determines that a code change is urgently needed to fix a bug in previously released code, the pull request workflow is modified in the following ways.
> 
> - Create your feature branch off of the master branch, not develop. The convention is to include the word "hotfix" in the name of the branch.
> ```

I think we want to be clear and say that the convention is use the`hotfix/` prefix. Similar, use the `hf-merge/` prefix when merging into develop.
___
*[docs/docs/Contributor-Guide.md, line 144 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg6Zu2Z3jDWrrvpZHmC:-Mg6Zu2Z3jDWrrvpZHmD:bwegw) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/4324c00c4e81e6e43d4f2d04fa54d9937b85231b/docs/docs/Contributor-Guide.md#L144)):*
> ```Markdown
> - Merge the master branch into your hotfix-merge branch.
> - Create a pull request for this branch as described above in the Contributor Instructions, using develop as the 'base:' branch, and your hotfix-merge branch as the 'compare:' branch.
> - The remainder of the process for reviewing and landing a PR to the develop branch must be followed at this point.
> ```

The process is different in that it's best to land the hf-merge branch on the command line in order to preserve the commits. Otherwise, if the user were to land the PR normally, they would do so via the GitHub UI and squash the commits into one, which we want to avoid.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: all files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 138 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg6YuER0zFJ3492G0YQ:-Mg6wzXnBVnwPpCF5cZa:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/4324c00c4e81e6e43d4f2d04fa54d9937b85231b/docs/docs/Contributor-Guide.md#L138)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we want to be clear and say that the convention is use the`hotfix/` prefix. Similar, use the `hf-merge/` prefix when merging into develop.
</blockquote></details>

Done.
___
*[docs/docs/Contributor-Guide.md, line 144 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg6Zu2Z3jDWrrvpZHmC:-Mg6xcl5AvwxB2IN0Pih:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/4324c00c4e81e6e43d4f2d04fa54d9937b85231b/docs/docs/Contributor-Guide.md#L144)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The process is different in that it's best to land the hf-merge branch on the command line in order to preserve the commits. Otherwise, if the user were to land the PR normally, they would do so via the GitHub UI and squash the commits into one, which we want to avoid.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 144 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg72DKHDXuptpieLzab:-Mg72DKHDXuptpieLzac:b-isu4ye) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L144)):*
> ```Markdown
> - Merge the master branch into your hf-merge branch.
> - Create a pull request for this branch as described above in the Contributor Instructions, using develop as the 'base:' branch, and your hf-merge branch as the 'compare:' branch.
> - The remainder of the process for reviewing and landing a PR to the develop branch must be followed at this point, with one exception. You should merge your branch to the develop branch on the command line, instead of through the github UI, to preserve commits and not squash them into one.
> ```

Capitalize "GitHub."

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: all files reviewed, 1 unresolved discussion (waiting on @clnowacki)

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 144 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg72DKHDXuptpieLzab:-Mg75KBp10DJfawIFCty:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L144)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Capitalize "GitHub."
</blockquote></details>

Done.

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 141 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg74NVB4g4VXJf6sj5f:-Mg74NVB4g4VXJf6sj5g:b-8g0her) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L141)):*
> ```Markdown
> - When creating your pull request on the web page for the repo you are modifying, leave the 'base:master' dropdown menu as is, and change the 'compare:' dropdown to the name of your hotfix branch.
> - After the PR has been reviewed and accepted, land the PR as described above.
> - Next, create a new branch off of the develop branch. The convention is to use the prefix "hf-merge/" in the name of the branch.
> ```

I think we should provide the commands here:
```shell
git checkout master
git pull
git checkout develop
git pull
git checkout -b hf-merge/<branch-name>
git merge master
git push -u
```
___
*[docs/docs/Contributor-Guide.md, line 144 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg763ao747gXbEl9Tc-:-Mg763ao747gXbEl9Tc0:b-w6l3j4) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L144)):*
> ```Markdown
> - Merge the master branch into your hf-merge branch.
> - Create a pull request for this branch as described above in the Contributor Instructions, using develop as the 'base:' branch, and your hf-merge branch as the 'compare:' branch.
> - The remainder of the process for reviewing and landing a PR to the develop branch must be followed at this point, with one exception. You should merge your branch to the develop branch on the command line, instead of through the github UI, to preserve commits and not squash them into one.
> ```

I think we should provide the commands here:
```shell
git checkout develop
git pull
git merge hf-merge/<branch-name>
```
Make sure it is a fast-forward merge
```shell
git push
```

**Comment by jrobble** [comment]
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg78DGO2UBmn38KyHck:-Mg78DGP0liyoB34_9Xq:by3liec) (no related file):*
Looks good to me. Will generate site files once @brosenberg42 approves.

---

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 141 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg74NVB4g4VXJf6sj5f:-Mg7E4fk0UzWb4A3CLlS:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L141)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think we should provide the commands here:
```shell
git checkout master
git pull
git checkout develop
git pull
git checkout -b hf-merge/<branch-name>
git merge master
git push -u
```

</blockquote></details>

Done.
___
*[docs/docs/Contributor-Guide.md, line 144 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/133#-Mg763ao747gXbEl9Tc-:-Mg7E5NEANmyye1WpKvc:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/214c5672748ddb8db0da4a0bc79166eba0c8c8b3/docs/docs/Contributor-Guide.md#L144)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think we should provide the commands here:
```shell
git checkout develop
git pull
git merge hf-merge/<branch-name>
```
Make sure it is a fast-forward merge
```shell
git push
```
</blockquote></details>

Done.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Pull request merged**
