### PR TITLE
Update release notes for R7.1.1.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1634
- https://github.com/openmpf/openmpf/issues/1524

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/1633
- https://github.com/openmpf/openmpf-components/pull/314
- https://github.com/openmpf/openmpf-contrib-components/pull/85
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/118
- https://github.com/openmpf/openmpf-java-component-sdk/pull/60
- https://github.com/openmpf/openmpf-python-component-sdk/pull/70

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[`docs/docs/Release-Notes.md` line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/160#-NJe_yF79p40l6U-lIla:-NJg7-I91G7H-86fXk_M:b662lwv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c2a2bae358e184ede785418c12547b00a2fea6a9/docs/docs/Release-Notes.md#L30)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In Markdown a single newline doesn't result in a new line in the rendered text. In order to get a new line in the rendered text, you actually need two newline characters in a row. For future reference, this is the correct way to write this:
```
- These properties affect all video and image components that use the MPFImageReader and
  MPFVideoCapture tools. When true, if the image has EXIF data, or there is metadata associated
  with a video that ffmpeg understands, the tools will use that information to properly orient the
  frames before returning the frames to the component for processing.
```
compare with the current version:
```
- These properties affect all video and image components that use the MPFImageReader and MPFVideoCapture tools. When true, if the image has EXIF data, or there is metadata associated with a video that ffmpeg understands, the tools will use that information to properly orient the frames before returning the frames to the component for processing.
```
</blockquote></details>

Wrapped lines.
___
*[`docs/docs/Release-Notes.md` line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/160#-NJeftxn4Ol1xjCTXOJz:-NJg7CC715ANA80ymytB:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c2a2bae358e184ede785418c12547b00a2fea6a9/docs/docs/Release-Notes.md#L35)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

There shouldn't be a slash between `<S3_UPLOAD_OBJECT_KEY_PREFIX>` and `<file-hash-first-two-chars>`. We don't automatically add the slash. If the user wants the slash, they need to add it.
</blockquote></details>

Done.
___
*[`docs/docs/Release-Notes.md` line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf.github.io/160#-NJegZmn8FqpHi7p2zYD:-NJg82gUAPKyXFeca8GC:b-dkp1p9) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/c2a2bae358e184ede785418c12547b00a2fea6a9/docs/docs/Release-Notes.md#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

There are no folders or paths in S3. There are only buckets and object keys. A slash in an object key has no special meaning. `work/ab` and `work//ab` refer to two different objects. That is one of the reasons we don't automatically add a slash after the prefix. Some S3 UI's do show folders when a slash is used, but that is a UI design choice. It isn't part of the API.
</blockquote></details>

Removed mention of the folder.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`docs/docs/Release-Notes.md` line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/160#-NJjrJQvEe--GLwFlp6y:-NJjrJQvEe--GLwFlp6z:bwdnfgi) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/403fad0fa0c68fd0ce2b14f92754f67f7ef9c2f9/docs/docs/Release-Notes.md#L27)):*
> ```Markdown
>     - `FIRST`: Select the detection with the lowest frame number
>     - `LAST`: Select the detection with the highest frame number
>     - `MIDDLE`: Select the detection with the frame number closest the middle frame of the track, preferring the
> ```

"closest to the middle'

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[`docs/docs/Release-Notes.md` line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/160#-NJjrJQvEe--GLwFlp6y:-NJkMVoBCfU0XOFdTC3a:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/403fad0fa0c68fd0ce2b14f92754f67f7ef9c2f9/docs/docs/Release-Notes.md#L27)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"closest to the middle'
</blockquote></details>

Done.

**Review by clnowacki — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
