### PR TITLE
Clarify the difference between Docker and non-Docker behaviors

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1351
- https://github.com/openmpf/openmpf/issues/1329

**Related PRs:**

- https://github.com/openmpf/openmpf-components/pull/259
- https://github.com/openmpf/openmpf-contrib-components/pull/73

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 48 files at r1, 7 of 51 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 24 of 68 files reviewed, 3 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[docs/docs/CPP-Batch-Component-API.md, line 1065 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKPk4M6EtHHK6azwue:-McKPk4NCis8u1XdtRbA:b-qpst2r) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Batch-Component-API.md#L1065)):*
> ```Markdown
> ```  
> 
> Once built, components can be packaged into a .tar.gz containing the contents of the directory shown above for non-Docker deployments.
> ```

I think "for non-Docker deployments" should be shown more prominently. Either in the heading itself or at least above the file tree.
___
*[docs/docs/CPP-Streaming-Component-API.md, line 63 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKSKmB0d9tvdau_BPE:-McKSKmB0d9tvdau_BPF:b-57ebzv) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Streaming-Component-API.md#L63)):*
> ```Markdown
> 1. Extending [`MPFStreamingDetectionComponent`](#detection-component-interface).
> 2. Building the component into a shared object library. (See [HelloWorldComponent CMakeLists.txt](https://github.com/openmpf/openmpf-cpp-component-sdk/blob/develop/detection/examples/HelloWorldComponent/CMakeLists.txt)).
> 3. Creating a component Docker image. (See the [README](https://github.com/openmpf/openmpf-docker/tree/master/components/cpp_executor#overview)).
> ```

I don't understand why you are mentioning creating a Docker image here when streaming doesn't work with Docker.
___
*[docs/docs/Python-Batch-Component-API.md, line 121 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKUHOWEVA4X3Xu0EDy:-McKUHOWEVA4X3Xu0EDz:bm2pcwk) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Python-Batch-Component-API.md#L121)):*
> ```Markdown
> setuptools and pip for dependency management.
> 
> 3. Creating a component Docker image. (See the [README](https://github.com/openmpf/openmpf-docker/tree/master/components/cpp_executor#overview)).
> ```

It looks like you copied this from the other pages, but it doesn't make sense here without any context. It also links to the C++ readme, not the Python one.

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 3 of 48 files at r1, 46 of 51 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: all files reviewed, 12 unresolved discussions (waiting on @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 33 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK8kUt5cDlm_fuyarP:-McK8kUu6mpM39rNTyHo:b-l9glzw) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Contributor-Guide.md#L33)):*
> ```Markdown
> - Designed to use existing interfaces, super classes, and utilities
> - Makes use of well-known design patterns, polymorphism, and encapsulation where possible
> - Employs best practices for integrating with the OpenMPF architecture. Refer to the [C++ Batch Component API](CPP-Batch-Component-API/index.html), [C++ Streaming Component API](CPP-Streaming-Component-API/index.html), and [Java Batch Component API](Java-Batch-Component-API/index.html).
> ```

Don't we have a python component API doc too?
___
*[docs/docs/CPP-Batch-Component-API.md, line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLKtwUA_EuFA7URAbn:-McLKtwUA_EuFA7URAbo:b-f0a5kt) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Batch-Component-API.md#L8)):*
> ```Markdown
> In OpenMPF, a **component** is a plugin that receives jobs (containing media), processes that  media, and returns results.
> 
> The OpenMPF Batch Component API currently supports the development of **detection components**, which are used detect objects in image, video, audio, or other (generic) files that reside on disk.
> ```

"...which are used *to* detect objects..."
___
*[docs/site/Development-Environment-Guide/index.html, line 352 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLOj0q4AqLVlO7LNtV:-McLOj0q4AqLVlO7LNtW:b-vyes0d) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Development-Environment-Guide/index.html#L352)):*
> ```HTML
> 
> <h1 id="overview">Overview</h1>
> <p>The following instructions are for setting up an environment for building and running OpenMPF outside of Docker. They serve as a reference for developers who want develop the Workflow Manager web application itself and perform end-to-end integration testing.</p>
> ```

"... for developers who want *to* develop..."
___
*[docs/site/Media-Segmentation-Guide/index.html, line 315 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLQZsy2h8kmqeTktcn:-McLQZsy2h8kmqeTktco:b3mczr6) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Media-Segmentation-Guide/index.html#L315)):*
> ```HTML
> <li>Segmenting must be performed on a video which has passed through a preprocessor or filter.</li>
> </ol>
> <p>In the first scenario the segmenting logic is less complex. The segmenter will create a supersegment corresponding to the entire length of the video (in frames), and it will then divide the supersegment into segments which respect to the provided "TARGET_SEGMENT_LENGTH" and "MIN_SEGMENT_LENGTH" properties.</p>
> ```

"... which respect the provided... " (remove 'to')
___
*[docs/docs/Component-Descriptor-Reference.md, line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK4qgBBpEg2hu_M1or:-McK4qgBBpEg2hu_M1os:bgh5f3i) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L42)):*
> ```Markdown
> Required.
> 
> Contains the language the component is coded in. Should be either “java” or “c++”.
> ```

Add python to the list of languages.
___
*[docs/docs/Component-Descriptor-Reference.md, line 76 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK5Aom0rMVdASTsqLS:-McK5AonAhFXhgbFgRNg:bx8heiy) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L76)):*
> ```Markdown
> For C++ components, this contains the full path to the Component Logic shared object library used for stream processing once the component is deployed.
> 
> Note that Java components currently do not support stream processing, so this field should be omitted from Java component descriptor files.
> ```

Applies to python as well.
___
*[docs/docs/Component-Descriptor-Reference.md, line 78 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK5Iz_86QmI9741nhR:-McK5Iz_86QmI9741nhS:bl3e6k2) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L78)):*
> ```Markdown
> Note that Java components currently do not support stream processing, so this field should be omitted from Java component descriptor files.
> 
>

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 45 of 70 files reviewed, 12 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[docs/docs/Contributor-Guide.md, line 33 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK8kUt5cDlm_fuyarP:-McPwhyO3qOJbzWdexlu:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Contributor-Guide.md#L33)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Don't we have a python component API doc too?
</blockquote></details>

Done.
___
*[docs/docs/CPP-Batch-Component-API.md, line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLKtwUA_EuFA7URAbn:-McPwpnf4wPEY2EYXjko:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Batch-Component-API.md#L8)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"...which are used *to* detect objects..."
</blockquote></details>

Done.
___
*[docs/docs/CPP-Batch-Component-API.md, line 1065 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKPk4M6EtHHK6azwue:-McLUagH32BUzzD48NVC:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Batch-Component-API.md#L1065)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think "for non-Docker deployments" should be shown more prominently. Either in the heading itself or at least above the file tree.
</blockquote></details>

Done.
___
*[docs/docs/CPP-Streaming-Component-API.md, line 63 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKSKmB0d9tvdau_BPE:-McLTdKU1_U7iD3i4J5J:b-ht0k22) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/CPP-Streaming-Component-API.md#L63)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't understand why you are mentioning creating a Docker image here when streaming doesn't work with Docker.
</blockquote></details>

Good catch. Just a copy mistake from updating the batch API.
___
*[docs/docs/Python-Batch-Component-API.md, line 121 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McKUHOWEVA4X3Xu0EDy:-McLUqHcEwHsXtP2z41D:bapitc2) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Python-Batch-Component-API.md#L121)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It looks like you copied this from the other pages, but it doesn't make sense here without any context. It also links to the C++ readme, not the Python one.
</blockquote></details>

Good catch. I dropped this here as a reminder but didn't do anything with it.
___
*[docs/site/Development-Environment-Guide/index.html, line 352 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLOj0q4AqLVlO7LNtV:-McPxmwr7fq3o9CZUc-r:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Development-Environment-Guide/index.html#L352)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"... for developers who want *to* develop..."
</blockquote></details>

Done.
___
*[docs/site/Media-Segmentation-Guide/index.html, line 315 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLQZsy2h8kmqeTktcn:-McPz_jt2sOrDAC8t4Ya:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Media-Segmentation-Guide/index.html#L315)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"... which respect the provided... " (remove 'to')
</blockquote></details>

Done.
___
*[docs/docs/Component-Descriptor-Reference.md, line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK4qgBBpEg2hu_M1or:-McPvcuXCoQBAXP8KIPV:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L42)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Add python to the list of languages.
</blockquote></details>

Done.
___
*[docs/docs/Component-Descriptor-Reference.md, line 76 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK5Aom0rMVdASTsqLS:-McPvltd8aQwACcq7yME:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L76)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Applies to python as well.
</blockquote></details>

Done.
___
*[docs/docs/Component-Descriptor-Reference.md, line 78 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McK5Iz_86QmI9741nhR:-McPvt813Sidp62BZFEi:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/docs/Component-Descriptor-Reference.md#L78)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Maybe just omit these "For future use" sections, since we have no plans to implement Java or python streaming.
</blockquote></details>

Done.
___
*[docs/site/Component-Descriptor-Reference/index.html, line 291 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLNtERBEoycVsEiuq0:-McPwyDs8Ls4EStkW887:bepsqv4) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Component-Descriptor-Reference/index.html#L291)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Do you want to change "In order to be registered..." to "In order to be used..." ?
</blockquote></details>

I think "registered" is still appropriate. It's just that registration is done automatically in a Docker deployment.
___
*[docs/site/Workflow-Manager-Architecture/index.html, line 323 at r2](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McLS1QREwA3kQtazRm5:-McPzrri2Q9CWdOnLZpi:b-ycq2oj) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/bd90eb14eefb0b44f164b9344aa53febdf9a9b25/docs/site/Workflow-Manager-Architecture/index.html#L323)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Why does this say OpenMPF 0.10.0? Has it really been that long since it was last updated?
</blockquote></details>

I checked, and that's honestly the last time we updated this doc for anything other than updating links and changing "mySQL" to "SQL". It was done to support the push to GitHub. Most of the content is still valid.

I didn't want to take the time to fully review the doc for correctness when I first created this PR, but I decided to bite the bullet and do it while addressing the other PR comments. 

I don't want to go into details with the individual Camel processors. I think the updated version gives a lot of good information without being too specific and potentially requiring a lot of future updates.

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 25 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 54 of 70 files reviewed, 11 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[docs/docs/Workflow-Manager-Architecture.md, line 33 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McUlUqQEwPmS6i25DJd:-McUlUqQEwPmS6i25DJe:b-b0sl0k) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1bbbd4607d7f55059d76a53b4179046fe9d407ac/docs/docs/Workflow-Manager-Architecture.md#L33)):*
> ```Markdown
>     * Job priority
>     * Job input/outputs
> 2. A **Redis database** for storing transient data that is only necessary while the job is being run. Some of this data is used to generate the output which will later be persisted in long-term storage, and some is a temporary duplication of previously persisted data in active memory to avoid race conditions. This data includes:
> ```

This is no longer accurate. I think we can just get rid of most this. There is no duplication and does nothing to help with race conditions.
___
*[docs/docs/Workflow-Manager-Architecture.md, line 140 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McUm_KV0ez5VzsqZrJN:-McUm_KV0ez5VzsqZrJO:b-e91988) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1bbbd4607d7f55059d76a53b4179046fe9d407ac/docs/docs/Workflow-Manager-Architecture.md#L140)):*
> ```Markdown
> ## Job Router Route
> 
> By the time the **Job Router Route** route is invoked, the job has been persisted in the permanent SQL database and the particulars of the pipeline and job request have been stored in Redis.
> ```

The part that mentions Redis is no longer accurate.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 54 of 70 files reviewed, 11 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[docs/docs/Workflow-Manager-Architecture.md, line 33 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McUlUqQEwPmS6i25DJd:-McV1r6iBpjQhcRUiiWF:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1bbbd4607d7f55059d76a53b4179046fe9d407ac/docs/docs/Workflow-Manager-Architecture.md#L33)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is no longer accurate. I think we can just get rid of most this. There is no duplication and does nothing to help with race conditions.
</blockquote></details>

Done.
___
*[docs/docs/Workflow-Manager-Architecture.md, line 140 at r3](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McUm_KV0ez5VzsqZrJN:-McV02124mzE7-C4v3g2:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/1bbbd4607d7f55059d76a53b4179046fe9d407ac/docs/docs/Workflow-Manager-Architecture.md#L140)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The part that mentions Redis is no longer accurate.
</blockquote></details>

Done.

**Review by brosenberg42 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 54 of 70 files reviewed, 9 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 11 of 25 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 69 of 70 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[docs/site/Development-Environment-Guide/index.html, line 770 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McVFVnlBbM5xQn8clq9:-McVFVnlBbM5xQn8clqA:b-qow220) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/92a6c654a8f90aa2feb8d518e69fb54e4a75e42c/docs/site/Development-Environment-Guide/index.html#L770)):*
> ```HTML
> <p>In a non-Docker deployment, admin users can register component packages through the web UI. Refer to <a href="#component-registration">Component Registration</a>.</p>
> <p>Once the descriptor file is complete, as described in <a href="../Component-Descriptor-Reference/index.html">Component Descriptor Reference</a>, the next step is to compile your component source code, and finally, create a .tar.gz package containing the descriptor file, component library, and all other necessary files.</p>
> <p>The package should contain a top-level directory with a unique name that will (hopefully) not conflict with existing component packages that have already been developed. The top-level directory name should be the same as the <code>componentName</code>.</p>
> ```

Remove (hopefully). The user can see all of the names of other components, except the proprietary ones, which we aren't giving them any clue about, so saying "hopefully" here is meaningless.
___
*[docs/site/Workflow-Manager-Architecture/index.html, line 485 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McVCZNH6jciX-keP-k6:-McVCZNH6jciX-keP-k7:bdl2g9o) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/92a6c654a8f90aa2feb8d518e69fb54e4a75e42c/docs/site/Workflow-Manager-Architecture/index.html#L485)):*
> ```HTML
> <h2 id="other-routes-not-shown">Other Routes <small><i>(Not Shown)</i></small></h2>
> <p>Additionally, there is a <strong>Detection Cancellation Route</strong> for cancelling detection requests sent to components, and a <strong>Markup Cancellation Route</strong> for cancelling requests sent to the Markup component. </p>
> <p>Also, there is a <strong>DLQ Route</strong> for handing messages that appear the ActiveMQ Dead Letter Queue (DLQ), which usually indicates a component failure or inability to deliver a message. In these cases, the job is terminated with an error condition.</p>
> ```

spelling of "handling"
"messages that appear *in* the ActiveMQ Dead Letter Queue"

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 69 of 70 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[docs/site/Development-Environment-Guide/index.html, line 770 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McVFVnlBbM5xQn8clq9:-McW7cry7bfafYRmKmKf:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/92a6c654a8f90aa2feb8d518e69fb54e4a75e42c/docs/site/Development-Environment-Guide/index.html#L770)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Remove (hopefully). The user can see all of the names of other components, except the proprietary ones, which we aren't giving them any clue about, so saying "hopefully" here is meaningless.
</blockquote></details>

Done.
___
*[docs/site/Workflow-Manager-Architecture/index.html, line 485 at r4](https://reviewable.io/reviews/openmpf/openmpf.github.io/130#-McVCZNH6jciX-keP-k6:-McW7cET64LVYi5vTX8w:b-896fix) ([raw file](https://github.com/openmpf/openmpf.github.io/blob/92a6c654a8f90aa2feb8d518e69fb54e4a75e42c/docs/site/Workflow-Manager-Architecture/index.html#L485)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

spelling of "handling"
"messages that appear *in* the ActiveMQ Dead Letter Queue"
</blockquote></details>

Done.

**Review by clnowacki — APPROVED** [review]
> Reviewed 9 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf.github.io/130)* status: 70 of 72 files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
